/*
 * Copyright (C) 2004-2012  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.instanceOfQuery;

import com.exedio.cope.ItemField;

class WIoqSourceSubB extends IoqSourceSuper // TODO rename to IoqSourceSubB
{
	static final ItemField<IoqSourceSubA> brother = ItemField.create(IoqSourceSubA.class);

	/**

	 **
	 * Creates a new WIoqSourceSubB with all the fields initially needed.
	 * @param ref the initial value for field {@link #ref}.
	 * @param code the initial value for field {@link #code}.
	 * @param brother the initial value for field {@link #brother}.
	 * @throws com.exedio.cope.MandatoryViolationException if ref, code, brother is null.
	 * @throws com.exedio.cope.StringLengthViolationException if code violates its length constraint.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	WIoqSourceSubB(
				final com.exedio.cope.instanceOfQuery.IoqTargetSuper ref,
				final java.lang.String code,
				final IoqSourceSubA brother)
			throws
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.StringLengthViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]{
			com.exedio.cope.instanceOfQuery.IoqSourceSuper.ref.map(ref),
			com.exedio.cope.instanceOfQuery.IoqSourceSuper.code.map(code),
			WIoqSourceSubB.brother.map(brother),
		});
	}/**

	 **
	 * Creates a new WIoqSourceSubB and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	protected WIoqSourceSubB(final com.exedio.cope.SetValue<?>... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Returns the value of {@link #brother}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final IoqSourceSubA getBrother()
	{
		return WIoqSourceSubB.brother.get(this);
	}/**

	 **
	 * Sets a new value for {@link #brother}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setBrother(final IoqSourceSubA brother)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		WIoqSourceSubB.brother.set(this,brother);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for wIoqSourceSubB.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	static final com.exedio.cope.Type<WIoqSourceSubB> TYPE = com.exedio.cope.TypesBound.newType(WIoqSourceSubB.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	protected WIoqSourceSubB(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
