
package com.exedio.cope.lib;

/**
 * @persistent
 */
public class StringItem extends Item
{
	static final StringAttribute any = new StringAttribute(DEFAULT);

	static final StringAttribute min4 = new StringAttribute(DEFAULT, 4);

/**

	 **
	 * Constructs a new StringItem with all the attributes initially needed.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public StringItem()
	{
		super(new com.exedio.cope.lib.AttributeValue[]{
		});
	}/**

	 **
	 * Reactivation constructor. Used for internal purposes only.
	 * <p><small>Generated by the cope instrumentor.</small>
	 * @see Item#Item(com.exedio.cope.lib.util.ReactivationConstructorDummy,int)
	 *
 */private StringItem(com.exedio.cope.lib.util.ReactivationConstructorDummy d,final int pk)
	{
		super(d,pk);
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #any}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */final String getAny()
	{
		return (String)getAttribute(this.any);
	}/**

	 **
	 * Sets a new value for the persistent attribute {@link #any}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */final void setAny(final String any)
	{
		try
		{
			setAttribute(this.any,any);
		}
		catch(com.exedio.cope.lib.LengthViolationException e)
		{
			throw new com.exedio.cope.lib.SystemException(e);
		}
		catch(com.exedio.cope.lib.NotNullViolationException e)
		{
			throw new com.exedio.cope.lib.SystemException(e);
		}
		catch(com.exedio.cope.lib.ReadOnlyViolationException e)
		{
			throw new com.exedio.cope.lib.SystemException(e);
		}
		catch(com.exedio.cope.lib.UniqueViolationException e)
		{
			throw new com.exedio.cope.lib.SystemException(e);
		}
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #min4}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */final String getMin4()
	{
		return (String)getAttribute(this.min4);
	}/**

	 **
	 * Sets a new value for the persistent attribute {@link #min4}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */final void setMin4(final String min4)
			throws
				com.exedio.cope.lib.LengthViolationException
	{
		try
		{
			setAttribute(this.min4,min4);
		}
		catch(com.exedio.cope.lib.NotNullViolationException e)
		{
			throw new com.exedio.cope.lib.SystemException(e);
		}
		catch(com.exedio.cope.lib.ReadOnlyViolationException e)
		{
			throw new com.exedio.cope.lib.SystemException(e);
		}
		catch(com.exedio.cope.lib.UniqueViolationException e)
		{
			throw new com.exedio.cope.lib.SystemException(e);
		}
	}/**

	 **
	 * The persistent type information for stringItem.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public static final com.exedio.cope.lib.Type TYPE = 
		new com.exedio.cope.lib.Type(StringItem.class)
;}
