language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

addons:
  postgresql: "9.3"

before_script:
  - echo -e "[server]\nmax_allowed_packet=64M" | sudo tee -a /etc/mysql/conf.d/cope.cnf
  - sudo service mysql restart
  - rm conf/environment/hsqldb-extra.properties
  - rm conf/environment/hsqldb-noPrep.properties
  - mysql -e 'create database cope_test;'
  - psql  -c 'create database cope_test;' -U postgres
  - echo -e -n \
    "connection.url=jdbc:mysql://localhost/cope_test\n"\
    "connection.username=travis\n"\
    "connection.password=\n"\
    "x-build.driver=mysql-connector-java.jar\n"\
    > conf/environment/mysql.properties
  - echo -e -n \
    "connection.url=jdbc:mysql://localhost/cope_test\n"\
    "connection.username=travis\n"\
    "connection.password=\n"\
    "schema.primaryKeyGenerator=sequence\n"\
    "x-build.driver=mysql-connector-java.jar\n"\
    > conf/environment/mysql-seq.properties
  - echo -e -n \
    "connection.url=jdbc:mysql://localhost/cope_test\n"\
    "connection.username=travis\n"\
    "connection.password=\n"\
    "disableSupport.preparedStatements=true\n"\
    "x-build.driver=mysql-connector-java.jar\n"\
    > conf/environment/mysql-noPrep.properties
  - echo -e -n \
    "connection.url=jdbc:postgresql://localhost/cope_test\n"\
    "connection.username=postgres\n"\
    "connection.password=\n"\
    "connection.postgresql.search_path=public\n"\
    "x-build.driver=postgresql.jar\n"\
    > conf/environment/postgresql.properties
  - echo -e -n \
    "connection.url=jdbc:postgresql://localhost/cope_test\n"\
    "connection.username=postgres\n"\
    "connection.password=\n"\
    "connection.postgresql.search_path=public\n"\
    "schema.primaryKeyGenerator=sequence\n"\
    "x-build.driver=postgresql.jar\n"\
    > conf/environment/postgresql-seq.properties
  - echo -e -n \
    "connection.url=jdbc:postgresql://localhost/cope_test\n"\
    "connection.username=postgres\n"\
    "connection.password=\n"\
    "connection.postgresql.search_path=public\n"\
    "disableSupport.preparedStatements=true\n"\
    "x-build.driver=postgresql.jar\n"\
    > conf/environment/postgresql-noPrep.properties

script: "ant jenkins"

after_script:
  - cat build/testprotocol.html
  - cat build/*-catalina-start.log
  - cat build/*-catalina-stop.log
  - cat tomcat/logs/*.log
