dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8

before_install:
  - sudo mysql_upgrade
  - sudo service mysql restart

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
  postgresql: "9.5"

before_script:
  - mysql -e "SET GLOBAL max_allowed_packet=64000000;"
  - mysql -e 'CREATE DATABASE cope_test_db;'
  - >
    mysql -u root --password= -e
    "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE VIEW
    ON cope_test_db.* TO 'cope_test_user'@'localhost' IDENTIFIED BY 'pass';"
  - psql  -c 'CREATE DATABASE cope_test_db;' -U postgres
  - >
    echo -e -n
    "connection.url=jdbc:mysql://localhost/cope_test_db\n
    connection.username=cope_test_user\n
    connection.password=pass\n
    x-build.driver=mysql-connector-java.jar\n"
    | tee conf/environment/my.properties
  - >
    echo -e -n
    "connection.url=jdbc:mysql://localhost/cope_test_db\n
    connection.username=cope_test_user\n
    connection.password=pass\n
    disableSupport.preparedStatements=true\n
    x-build.driver=mysql-connector-java.jar\n"
    | tee conf/environment/my-nprep.properties
  - >
    echo -e -n
    "connection.url=jdbc:mysql://localhost/cope_test_db\n
    connection.username=cope_test_user\n
    connection.password=pass\n
    schema.primaryKeyGenerator=sequence\n
    x-build.driver=mysql-connector-java.jar\n"
    | tee conf/environment/my-sq.properties
  - >
    echo -e -n
    "connection.url=jdbc:mysql://localhost/cope_test_db\n
    connection.username=cope_test_user\n
    connection.password=pass\n
    schema.primaryKeyGenerator=sequence\n
    x-build.driver=mariadb-java-client.jar\n"
    | tee conf/environment/mym.properties
  - >
    echo -e -n
    "connection.url=jdbc:postgresql://localhost/cope_test_db\n
    connection.username=postgres\n
    connection.password=\n
    dialect.search_path=public\n
    x-build.driver=postgresql.jar\n"
    | tee conf/environment/pg.properties
  - >
    echo -e -n
    "connection.url=jdbc:postgresql://localhost/cope_test_db\n
    connection.username=postgres\n
    connection.password=\n
    dialect.search_path=public\n
    disableSupport.preparedStatements=true\n
    x-build.driver=postgresql.jar\n"
    | tee conf/environment/pg-nprep.properties
  - >
    echo -e -n
    "connection.url=jdbc:postgresql://localhost/cope_test_db\n
    connection.username=postgres\n
    connection.password=\n
    dialect.search_path=public\n
    schema.primaryKeyGenerator=sequence\n
    x-build.driver=postgresql.jar\n"
    | tee conf/environment/pg-sq.properties

script:
  - >
    ant clean jenkins
    '-Dbuild.tag=git ${TRAVIS_BRANCH} ${TRAVIS_COMMIT} travis-ci ${TRAVIS_BUILD_NUMBER} ${TRAVIS_JOB_NUMBER} ${TRAVIS_BUILD_ID} `date '+%G-%m-%d_%H:%M:%S'`'
    -Dtest-details=none
  - mkdir build/travis
  - cp build/testprotocol.* build/travis

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: build/travis
  keep-history: true
  allow-empty-commit: true
  debug: true
  on:
    all_branches: true

after_script:
  - cat build/*-catalina-start.log
  - cat build/*-catalina-stop.log
  - cat tomcat/logs/*.log
  - ls -la build/testtmpdir
