language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_script:
  - mysql -e 'create database cope_test;'
  - psql  -c 'create database cope_test;' -U postgres
  - echo -e -n \
    "connection.url=jdbc:mysql://localhost/cope_test\n"\
    "connection.username=travis\n"\
    "connection.password=\n"\
    "x-build.driver=mysql-connector-java.jar\n"\
    > conf/environment/mysql.properties
  - echo -e -n \
    "connection.url=jdbc:mysql://localhost/cope_test\n"\
    "connection.username=travis\n"\
    "connection.password=\n"\
    "schema.primaryKeyGenerator=sequence\n"\
    "x-build.driver=mysql-connector-java.jar\n"\
    > conf/environment/mysql-seq.properties
  - echo -e -n \
    "connection.url=jdbc:mysql://localhost/cope_test\n"\
    "connection.username=travis\n"\
    "connection.password=\n"\
    "disableSupport.preparedStatements=true\n"\
    "x-build.driver=mysql-connector-java.jar\n"\
    > conf/environment/mysql-noPrep.properties
  - echo -e -n \
    "connection.url=jdbc:postgresql://localhost/cope_test\n"\
    "connection.username=postgres\n"\
    "connection.password=\n"\
    "x-build.driver=postgresql.jar\n"\
    > conf/environment/postgresql.properties

script: "ant jenkins"
