dist: xenial
sudo: required
language: java
jdk:
  - openjdk8
  - openjdk11

before_install:
  - >
    echo -e -n
    "[server]\n
    server-id=1\n
    log_bin=/var/log/mysql/mysql-bin.log\n
    binlog_do_db=binlogtest\n
    gtid_mode=ON\n
    enforce_gtid_consistency=ON\n"
    | sudo tee /etc/mysql/conf.d/cope.cnf
  - sudo service mysql start

addons:
  postgresql: "9.6"

before_script:
  - mysql -e "SET GLOBAL max_allowed_packet=64000000;"
  - >
    echo -e -n
    "connection.url=jdbc:mysql://localhost/test_db_schema\n
    connection.username=test_db_user\n
    connection.password=test_db_password\n
    x-build.schemasavepoint=OK: SHOW MASTER STATUS Gtid=\\\\\p{XDigit}{8}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{12}:\\\\\d+-\\\\\d+ mysql-bin.\\\\\d{6}:\\\\\d+ doDB=binlogtest\n
    x-build.dialect=mysql\n
    x-build.driver=mysql-connector-java.jar\n"
    | tee conf/environment/my.properties
  - >
    echo -e -n
    "connection.url=jdbc:mysql://localhost/test_db_schema\n
    connection.username=test_db_user\n
    connection.password=test_db_password\n
    disableSupport.preparedStatements=true\n
    x-build.schemasavepoint=OK: SHOW MASTER STATUS Gtid=\\\\\p{XDigit}{8}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{12}:\\\\\d+-\\\\\d+ mysql-bin.\\\\\d{6}:\\\\\d+ doDB=binlogtest\n
    x-build.dialect=mysql\n
    x-build.driver=mysql-connector-java.jar\n"
    | tee conf/environment/my-nprep.properties
  - >
    echo -e -n
    "connection.url=jdbc:mysql://localhost/test_db_schema\n
    connection.username=test_db_user\n
    connection.password=test_db_password\n
    schema.primaryKeyGenerator=sequence\n
    x-build.schemasavepoint=OK: SHOW MASTER STATUS Gtid=\\\\\p{XDigit}{8}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{12}:\\\\\d+-\\\\\d+ mysql-bin.\\\\\d{6}:\\\\\d+ doDB=binlogtest\n
    x-build.dialect=mysql\n
    x-build.driver=mysql-connector-java.jar\n"
    | tee conf/environment/my-sq.properties
  - >
    echo -e -n
    "connection.url=jdbc:mysql://localhost/test_db_schema\n
    connection.username=test_db_user\n
    connection.password=test_db_password\n
    dialect.connection.compress=true\n
    schema.primaryKeyGenerator=sequence\n
    x-build.schemasavepoint=OK: SHOW MASTER STATUS Gtid=\\\\\p{XDigit}{8}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{12}:\\\\\d+-\\\\\d+ mysql-bin.\\\\\d{6}:\\\\\d+ doDB=binlogtest\n
    x-build.dialect=mysql\n
    x-build.driver=mysql-connector-java.jar\n"
    | tee conf/environment/my-z.properties
  - >
    echo -e -n
    "connection.url=jdbc:mysql://localhost/test_db_schema\n
    connection.username=test_db_user\n
    connection.password=test_db_password\n
    schema.primaryKeyGenerator=sequence\n
    x-build.schemasavepoint=OK: SHOW MASTER STATUS Gtid=\\\\\p{XDigit}{8}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{12}:\\\\\d+-\\\\\d+ mysql-bin.\\\\\d{6}:\\\\\d+ doDB=binlogtest\n
    x-build.dialect=mysql\n
    x-build.driver=mariadb-java-client.jar\n"
    | tee conf/environment/mym.properties
  - >
    echo -e -n
    "connection.url=jdbc:mysql://localhost/test_db_schema\n
    connection.username=test_db_user\n
    connection.password=test_db_password\n
    dialect.connection.compress=true\n
    schema.primaryKeyGenerator=sequence\n
    x-build.schemasavepoint=OK: SHOW MASTER STATUS Gtid=\\\\\p{XDigit}{8}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{4}-\\\\\p{XDigit}{12}:\\\\\d+-\\\\\d+ mysql-bin.\\\\\d{6}:\\\\\d+ doDB=binlogtest\n
    x-build.dialect=mysql\n
    x-build.driver=mariadb-java-client.jar\n"
    | tee conf/environment/mym-z.properties
  - >
    echo -e -n
    "connection.url=jdbc:postgresql://localhost/test_db_database\n
    connection.username=test_db_user\n
    connection.password=test_db_password\n
    dialect.connection.schema=test_db_schema\n
    dialect.pgcryptoSchema=test_db_pgcrypto_schema\n
    x-build.dialect=postgresql\n
    x-build.driver=postgresql.jar\n"
    | tee conf/environment/pg.properties
  - >
    echo -e -n
    "connection.url=jdbc:postgresql://localhost/test_db_database\n
    connection.username=test_db_user\n
    connection.password=test_db_password\n
    dialect.connection.schema=test_db_schema\n
    dialect.pgcryptoSchema=test_db_pgcrypto_schema\n
    disableSupport.preparedStatements=true\n
    x-build.dialect=postgresql\n
    x-build.driver=postgresql.jar\n"
    | tee conf/environment/pg-nprep.properties
  - >
    echo -e -n
    "connection.url=jdbc:postgresql://localhost/test_db_database\n
    connection.username=test_db_user\n
    connection.password=test_db_password\n
    dialect.connection.schema=test_db_schema\n
    dialect.pgcryptoSchema=test_db_pgcrypto_schema\n
    schema.primaryKeyGenerator=sequence\n
    dialect.pgcryptoSchema=<disabled>\n
    x-build.dialect=postgresql\n
    x-build.driver=postgresql.jar\n"
    | tee conf/environment/pg-sq.properties

script:
  - >
    ant/bin/ant -noinput clean jenkins
    '-Dbuild.tag=git ${TRAVIS_BRANCH} ${TRAVIS_COMMIT} travis-ci ${TRAVIS_BUILD_NUMBER} ${TRAVIS_JOB_NUMBER} ${TRAVIS_BUILD_ID} `date '+%G-%m-%d_%H:%M:%S'`'
    '-Druntime.test.withEnv.setup.mysql.url=jdbc:mysql://localhost/'
    '-Druntime.test.withEnv.setup.mysql.sql=conf/setup-mysql57.sql'
    '-Druntime.test.withEnv.setup.postgresql.url=jdbc:postgresql://localhost/'
    '-Druntime.test.withEnv.setup.password='
  - mkdir build/travis
  - cp build/testprotocol.* build/travis

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: build/travis
  keep-history: true
  allow-empty-commit: true
  debug: true
  on:
    all_branches: true

after_script:
  - cat build/*-catalina-start.log
  - cat build/*-catalina-stop.log
  - cat tomcat/logs/*.log
  - ls -la build/testtmpdir
