/*
 * Copyright (C) 2004-2009  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope;

class ConnectItem2 extends ConnectItem
{
	static final ItemField<ConnectItem> itemField2 = newItemField(ConnectItem.class).optional();
	static final ItemField<ConnectItem2> itemFieldSelf2 = newItemField(ConnectItem2.class).optional();
	static final StringField stringField2 = new StringField().optional();
	
	/**

	 **
	 * Creates a new ConnectItem2 with all the fields initially needed.
	 * @param itemField the initial value for field {@link #itemField}.
	 * @param itemFieldSelf the initial value for field {@link #itemFieldSelf}.
	 * @param stringField the initial value for field {@link #stringField}.
	 * @throws com.exedio.cope.MandatoryViolationException if itemField, itemFieldSelf, stringField is null.
	 * @throws com.exedio.cope.StringLengthViolationException if stringField violates its length constraint.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	ConnectItem2(
				final com.exedio.cope.ConnectItem2 itemField,
				final com.exedio.cope.ConnectItem itemFieldSelf,
				final java.lang.String stringField)
			throws
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.StringLengthViolationException
	{
		this(new com.exedio.cope.SetValue[]{
			ConnectItem2.itemField.map(itemField),
			ConnectItem2.itemFieldSelf.map(itemFieldSelf),
			ConnectItem2.stringField.map(stringField),
		});
	}/**

	 **
	 * Creates a new ConnectItem2 and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	private ConnectItem2(final com.exedio.cope.SetValue... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@SuppressWarnings("unused") private ConnectItem2(final com.exedio.cope.ActivationParameters ap)
	{
		super(ap);
	}/**

	 **
	 * Returns the value of {@link #itemField2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.ConnectItem getItemField2()
	{
		return ConnectItem2.itemField2.get(this);
	}/**

	 **
	 * Sets a new value for {@link #itemField2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setItemField2(final com.exedio.cope.ConnectItem itemField2)
	{
		ConnectItem2.itemField2.set(this,itemField2);
	}/**

	 **
	 * Returns the value of {@link #itemFieldSelf2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.ConnectItem2 getItemFieldSelf2()
	{
		return ConnectItem2.itemFieldSelf2.get(this);
	}/**

	 **
	 * Sets a new value for {@link #itemFieldSelf2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setItemFieldSelf2(final com.exedio.cope.ConnectItem2 itemFieldSelf2)
	{
		ConnectItem2.itemFieldSelf2.set(this,itemFieldSelf2);
	}/**

	 **
	 * Returns the value of {@link #stringField2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getStringField2()
	{
		return ConnectItem2.stringField2.get(this);
	}/**

	 **
	 * Sets a new value for {@link #stringField2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setStringField2(final java.lang.String stringField2)
			throws
				com.exedio.cope.StringLengthViolationException
	{
		ConnectItem2.stringField2.set(this,stringField2);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for connectItem2.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	static final com.exedio.cope.Type<ConnectItem2> TYPE = com.exedio.cope.TypesBound.newType(ConnectItem2.class)
;}
