/*
 * Copyright (C) 2004-2015  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope;

import static com.exedio.cope.instrument.Visibility.NONE;
import static org.junit.jupiter.api.Assertions.assertEquals;

import com.exedio.cope.instrument.WrapperType;
import org.junit.jupiter.api.Test;

public class CopyRedundantTest
{
	@Test void testIsRedundant()
	{
		assertEquals(false, AnItem.targetMan.isRedundantByCopyConstraint());
		assertEquals(false, AnItem.targetOpt.isRedundantByCopyConstraint());

		assertEquals(false, AnItem.copyNone .isRedundantByCopyConstraint());
		assertEquals(true,  AnItem.copyMan  .isRedundantByCopyConstraint());
		assertEquals(false, AnItem.copyOpt  .isRedundantByCopyConstraint());
		assertEquals(true,  AnItem.copyBoth .isRedundantByCopyConstraint());
	}

	@WrapperType(type=NONE, indent=2)
	private static final class AnItem extends Item
	{
		static final ItemField<AnItem> targetMan = ItemField.create(AnItem.class);
		static final ItemField<AnItem> targetOpt = ItemField.create(AnItem.class).optional();

		static final StringField copyNone = new StringField();
		static final StringField copyMan  = new StringField().copyFrom(targetMan, () -> AnItem.copyMan);
		static final StringField copyOpt  = new StringField().copyFrom(targetOpt, () -> AnItem.copyOpt);
		static final StringField copyBoth = new StringField().copyFrom(targetMan, () -> AnItem.copyBoth).copyFrom(targetOpt, () -> AnItem.copyBoth);


		@SuppressWarnings("unused") // OK: must not be generated by instrumentor
		void setCopyMan(final String copyMan)
		{
			AnItem.copyMan.set(this, copyMan);
		}

		@SuppressWarnings("unused") // OK: must not be generated by instrumentor
		void setCopyBoth(final String copyBoth)
		{
			AnItem.copyBoth.set(this, copyBoth);
		}


		/**
		 * Creates a new AnItem with all the fields initially needed.
		 * @param targetMan the initial value for field {@link #targetMan}.
		 * @param copyNone the initial value for field {@link #copyNone}.
		 * @param copyOpt the initial value for field {@link #copyOpt}.
		 * @throws com.exedio.cope.MandatoryViolationException if targetMan, copyNone, copyOpt is null.
		 * @throws com.exedio.cope.StringLengthViolationException if copyNone, copyOpt violates its length constraint.
		 */
		@com.exedio.cope.instrument.Generated // customize with @WrapperType(constructor=...) and @WrapperInitial
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedInnerClassAccess"})
		private AnItem(
					@javax.annotation.Nonnull final AnItem targetMan,
					@javax.annotation.Nonnull final java.lang.String copyNone,
					@javax.annotation.Nonnull final java.lang.String copyOpt)
				throws
					com.exedio.cope.MandatoryViolationException,
					com.exedio.cope.StringLengthViolationException
		{
			this(new com.exedio.cope.SetValue<?>[]{
				com.exedio.cope.SetValue.map(AnItem.targetMan,targetMan),
				com.exedio.cope.SetValue.map(AnItem.copyNone,copyNone),
				com.exedio.cope.SetValue.map(AnItem.copyOpt,copyOpt),
			});
		}

		/**
		 * Creates a new AnItem and sets the given fields initially.
		 */
		@com.exedio.cope.instrument.Generated // customize with @WrapperType(genericConstructor=...)
		private AnItem(final com.exedio.cope.SetValue<?>... setValues){super(setValues);}

		/**
		 * Returns the value of {@link #targetMan}.
		 */
		@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="get")
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
		@javax.annotation.Nonnull
		AnItem getTargetMan()
		{
			return AnItem.targetMan.get(this);
		}

		/**
		 * Sets a new value for {@link #targetMan}.
		 */
		@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="set")
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
		void setTargetMan(@javax.annotation.Nonnull final AnItem targetMan)
				throws
					com.exedio.cope.MandatoryViolationException
		{
			AnItem.targetMan.set(this,targetMan);
		}

		/**
		 * Returns the value of {@link #targetOpt}.
		 */
		@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="get")
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
		@javax.annotation.Nullable
		AnItem getTargetOpt()
		{
			return AnItem.targetOpt.get(this);
		}

		/**
		 * Sets a new value for {@link #targetOpt}.
		 */
		@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="set")
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
		void setTargetOpt(@javax.annotation.Nullable final AnItem targetOpt)
		{
			AnItem.targetOpt.set(this,targetOpt);
		}

		/**
		 * Returns the value of {@link #copyNone}.
		 */
		@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="get")
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
		@javax.annotation.Nonnull
		java.lang.String getCopyNone()
		{
			return AnItem.copyNone.get(this);
		}

		/**
		 * Sets a new value for {@link #copyNone}.
		 */
		@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="set")
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
		void setCopyNone(@javax.annotation.Nonnull final java.lang.String copyNone)
				throws
					com.exedio.cope.MandatoryViolationException,
					com.exedio.cope.StringLengthViolationException
		{
			AnItem.copyNone.set(this,copyNone);
		}

		/**
		 * Returns the value of {@link #copyMan}.
		 */
		@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="get")
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
		@javax.annotation.Nonnull
		java.lang.String getCopyMan()
		{
			return AnItem.copyMan.get(this);
		}

		/**
		 * Returns the value of {@link #copyOpt}.
		 */
		@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="get")
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
		@javax.annotation.Nonnull
		java.lang.String getCopyOpt()
		{
			return AnItem.copyOpt.get(this);
		}

		/**
		 * Sets a new value for {@link #copyOpt}.
		 */
		@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="set")
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
		void setCopyOpt(@javax.annotation.Nonnull final java.lang.String copyOpt)
				throws
					com.exedio.cope.MandatoryViolationException,
					com.exedio.cope.StringLengthViolationException
		{
			AnItem.copyOpt.set(this,copyOpt);
		}

		/**
		 * Returns the value of {@link #copyBoth}.
		 */
		@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="get")
		@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
		@javax.annotation.Nonnull
		java.lang.String getCopyBoth()
		{
			return AnItem.copyBoth.get(this);
		}

		@com.exedio.cope.instrument.Generated
		@java.io.Serial
		private static final long serialVersionUID = 1l;

		/**
		 * Activation constructor. Used for internal purposes only.
		 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
		 */
		@com.exedio.cope.instrument.Generated
		private AnItem(final com.exedio.cope.ActivationParameters ap){super(ap);}
	}
}
