/*
 * Copyright (C) 2004-2015  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope;

final class CopyTargetItem extends Item
{
	/**
	 * @cope.initial
	 */
	static final StringField templateString = new StringField().toFinal().optional();
	static final StringField otherString = new StringField();

	/**
	 * @cope.initial
	 */
	static final ItemField<CopyValueItem> templateItem = ItemField.create(CopyValueItem.class).toFinal().optional();
	static final ItemField<CopyValueItem> otherItem = ItemField.create(CopyValueItem.class);

	@Override
	public String toString()
	{
		// for testing, that CopyViolation#getMessage does not call toString(), but getCopeID()
		return "toString(" + getCopeID() + ')';
	}

	/**

	 **
	 * Creates a new CopyTargetItem with all the fields initially needed.
	 * @param templateString the initial value for field {@link #templateString}.
	 * @param otherString the initial value for field {@link #otherString}.
	 * @param templateItem the initial value for field {@link #templateItem}.
	 * @param otherItem the initial value for field {@link #otherItem}.
	 * @throws com.exedio.cope.MandatoryViolationException if otherString, otherItem is null.
	 * @throws com.exedio.cope.StringLengthViolationException if templateString, otherString violates its length constraint.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	CopyTargetItem(
				@javax.annotation.Nullable final java.lang.String templateString,
				@javax.annotation.Nonnull final java.lang.String otherString,
				@javax.annotation.Nullable final CopyValueItem templateItem,
				@javax.annotation.Nonnull final CopyValueItem otherItem)
			throws
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.StringLengthViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]{
			CopyTargetItem.templateString.map(templateString),
			CopyTargetItem.otherString.map(otherString),
			CopyTargetItem.templateItem.map(templateItem),
			CopyTargetItem.otherItem.map(otherItem),
		});
	}/**

	 **
	 * Creates a new CopyTargetItem and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private CopyTargetItem(final com.exedio.cope.SetValue<?>... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Returns the value of {@link #templateString}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@javax.annotation.Nullable
	final java.lang.String getTemplateString()
	{
		return CopyTargetItem.templateString.get(this);
	}/**

	 **
	 * Returns the value of {@link #otherString}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@javax.annotation.Nonnull
	final java.lang.String getOtherString()
	{
		return CopyTargetItem.otherString.get(this);
	}/**

	 **
	 * Sets a new value for {@link #otherString}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setOtherString(@javax.annotation.Nonnull final java.lang.String otherString)
			throws
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.StringLengthViolationException
	{
		CopyTargetItem.otherString.set(this,otherString);
	}/**

	 **
	 * Returns the value of {@link #templateItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@javax.annotation.Nullable
	final CopyValueItem getTemplateItem()
	{
		return CopyTargetItem.templateItem.get(this);
	}/**

	 **
	 * Returns the value of {@link #otherItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@javax.annotation.Nonnull
	final CopyValueItem getOtherItem()
	{
		return CopyTargetItem.otherItem.get(this);
	}/**

	 **
	 * Sets a new value for {@link #otherItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setOtherItem(@javax.annotation.Nonnull final CopyValueItem otherItem)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		CopyTargetItem.otherItem.set(this,otherItem);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for copyTargetItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final com.exedio.cope.Type<CopyTargetItem> TYPE = com.exedio.cope.TypesBound.newType(CopyTargetItem.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@SuppressWarnings("unused") private CopyTargetItem(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
