/*
 * Copyright (C) 2004-2009  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope;


public class PlusDoubleItem extends Item
{
	public static final DoubleField numA = new DoubleField().optional();

	public static final DoubleField numB = new DoubleField().optional();

	public static final DoubleField numC = new DoubleField().optional();
	
	public static final PlusLiteralView<Double> plusA9 = new PlusLiteralView<Double>(numA, new Double(9.3));
	
	public static final PlusView<Double> plusAB = numA.plus(numB);

	public static final PlusView<Double> plusAC = numA.plus(numC);

	public static final PlusView<Double> plusBC = numB.plus(numC);

	public static final PlusView<Double> plusABC = Cope.plus(numA, numB, numC);

	public static final PlusView<Double> plusABaC = plusAB.plus(numC);
	
	public static final MultiplyLiteralView<Double> multiplyB9 = new MultiplyLiteralView<Double>(numB, new Double(9.3));
	
	public static final MultiplyView<Double> multiplyBC = numB.multiply(numC);
	
	public PlusDoubleItem(final double initialNumA, final double initialNumB, final double initialNumC)
	{
		super(new SetValue[]{
			numA.map(initialNumA),
			numB.map(initialNumB),
			numC.map(initialNumC),
		});
	}

	/**

	 **
	 * Creates a new PlusDoubleItem with all the fields initially needed.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	public PlusDoubleItem()
	{
		this(new com.exedio.cope.SetValue[]{
		});
	}/**

	 **
	 * Creates a new PlusDoubleItem and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	private PlusDoubleItem(final com.exedio.cope.SetValue... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@SuppressWarnings("unused") private PlusDoubleItem(final com.exedio.cope.ActivationParameters ap)
	{
		super(ap);
	}/**

	 **
	 * Returns the value of {@link #numA}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getNumA()
	{
		return PlusDoubleItem.numA.get(this);
	}/**

	 **
	 * Sets a new value for {@link #numA}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final void setNumA(final java.lang.Double numA)
	{
		PlusDoubleItem.numA.set(this,numA);
	}/**

	 **
	 * Returns the value of {@link #numB}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getNumB()
	{
		return PlusDoubleItem.numB.get(this);
	}/**

	 **
	 * Sets a new value for {@link #numB}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final void setNumB(final java.lang.Double numB)
	{
		PlusDoubleItem.numB.set(this,numB);
	}/**

	 **
	 * Returns the value of {@link #numC}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getNumC()
	{
		return PlusDoubleItem.numC.get(this);
	}/**

	 **
	 * Sets a new value for {@link #numC}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final void setNumC(final java.lang.Double numC)
	{
		PlusDoubleItem.numC.set(this,numC);
	}/**

	 **
	 * Returns the value of {@link #plusA9}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getPlusA9()
	{
		return PlusDoubleItem.plusA9.get(this);
	}/**

	 **
	 * Returns the value of {@link #plusAB}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getPlusAB()
	{
		return PlusDoubleItem.plusAB.get(this);
	}/**

	 **
	 * Returns the value of {@link #plusAC}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getPlusAC()
	{
		return PlusDoubleItem.plusAC.get(this);
	}/**

	 **
	 * Returns the value of {@link #plusBC}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getPlusBC()
	{
		return PlusDoubleItem.plusBC.get(this);
	}/**

	 **
	 * Returns the value of {@link #plusABC}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getPlusABC()
	{
		return PlusDoubleItem.plusABC.get(this);
	}/**

	 **
	 * Returns the value of {@link #plusABaC}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getPlusABaC()
	{
		return PlusDoubleItem.plusABaC.get(this);
	}/**

	 **
	 * Returns the value of {@link #multiplyB9}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getMultiplyB9()
	{
		return PlusDoubleItem.multiplyB9.get(this);
	}/**

	 **
	 * Returns the value of {@link #multiplyBC}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final java.lang.Double getMultiplyBC()
	{
		return PlusDoubleItem.multiplyBC.get(this);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for plusDoubleItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	public static final com.exedio.cope.Type<PlusDoubleItem> TYPE = newType(PlusDoubleItem.class)
;}
