/*
 * Copyright (C) 2004-2006  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.testmodel;

import com.exedio.cope.IntegerAttribute;
import com.exedio.cope.Item;
import com.exedio.cope.StringAttribute;

/**
 * An item having a final attribute.
 * @cope.persistent
 * @author Ralf Wiebicke
 */
public class FinalItem extends Item
{
	public static final StringAttribute finalString = new StringAttribute(FINAL);
	public static final IntegerAttribute nonFinalInteger = new IntegerAttribute(MANDATORY);

/**

	 **
	 * Creates a new FinalItem with all the attributes initially needed.
	 * @param finalString the initial value for attribute {@link #finalString}.
	 * @param nonFinalInteger the initial value for attribute {@link #nonFinalInteger}.
	 * @throws com.exedio.cope.LengthViolationException if finalString violates its length constraint.
	 * @throws com.exedio.cope.MandatoryViolationException if finalString is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <code>@cope.constructor public|package|protected|private|none</code> in the class comment and <code>@cope.initial</code> in the comment of attributes.
	 */
	public FinalItem(
				final java.lang.String finalString,
				final int nonFinalInteger)
			throws
				com.exedio.cope.LengthViolationException,
				com.exedio.cope.MandatoryViolationException
	{
		this(new com.exedio.cope.AttributeValue[]{
			FinalItem.finalString.map(finalString),
			FinalItem.nonFinalInteger.map(nonFinalInteger),
		});
	}/**

	 **
	 * Creates a new FinalItem and sets the given attributes initially.
	 * This constructor is called by {@link com.exedio.cope.Type#newItem Type.newItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <code>@cope.generic.constructor public|package|protected|private|none</code> in the class comment.
	 */
	private FinalItem(final com.exedio.cope.AttributeValue[] initialAttributes)
	{
		super(initialAttributes);
	}/**

	 **
	 * Reactivation constructor. Used for internal purposes only.
	 * @see Item#Item(com.exedio.cope.util.ReactivationConstructorDummy,int)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private FinalItem(com.exedio.cope.util.ReactivationConstructorDummy d,final int pk)
	{
		super(d,pk);
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #finalString}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <code>@cope.getter public|package|protected|private|none|non-final|boolean-as-is</code> in the comment of the attribute.
	 */
	public final java.lang.String getFinalString()
	{
		return FinalItem.finalString.get(this);
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #nonFinalInteger}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <code>@cope.getter public|package|protected|private|none|non-final|boolean-as-is</code> in the comment of the attribute.
	 */
	public final int getNonFinalInteger()
	{
		return FinalItem.nonFinalInteger.getMandatory(this);
	}/**

	 **
	 * Sets a new value for the persistent attribute {@link #nonFinalInteger}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <code>@cope.setter public|package|protected|private|none|non-final</code> in the comment of the attribute.
	 */
	public final void setNonFinalInteger(final int nonFinalInteger)
	{
		FinalItem.nonFinalInteger.set(this,nonFinalInteger);
	}/**

	 **
	 * The persistent type information for finalItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <code>@cope.type public|package|protected|private|none</code> in the class comment.
	 */
	public static final com.exedio.cope.Type TYPE =
		new com.exedio.cope.Type(FinalItem.class)
;}
