/*
 * Copyright (C) 2004-2005  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.testmodel;

import com.exedio.cope.Item;
import com.exedio.cope.StringAttribute;
import com.exedio.cope.pattern.Hash;
import com.exedio.cope.pattern.MD5Hash;

/**
 * @persistent
 * @author Ralf Wiebicke
 */
public class HashItem extends Item
{
	public static final StringAttribute hashed1MD5 = stringAttribute(DEFAULT);
	public static final MD5Hash hashed1 = new MD5Hash(hashed1MD5);
	public static final MD5Hash hashed1Latin = new MD5Hash(hashed1MD5, "ISO-8859-1");

	public static final StringAttribute hashed2Wrap = stringAttribute(DEFAULT);
	public static final Hash hashed2 = new WrapHash(hashed2Wrap);

/**

	 **
	 * Creates a new HashItem with all the attributes initially needed.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public HashItem()
	{
		this(new com.exedio.cope.AttributeValue[]{
		});
	}/**

	 **
	 * Creates a new HashItem and sets the given attributes initially.
	 * This constructor is called by {@link com.exedio.cope.Type#newItem Type.newItem}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */private HashItem(final com.exedio.cope.AttributeValue[] initialAttributes)
	{
		super(initialAttributes);
	}/**

	 **
	 * Reactivation constructor. Used for internal purposes only.
	 * <p><small>Generated by the cope instrumentor.</small>
	 * @see Item#Item(com.exedio.cope.util.ReactivationConstructorDummy,int)
	 *
 */private HashItem(com.exedio.cope.util.ReactivationConstructorDummy d,final int pk)
	{
		super(d,pk);
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #hashed1MD5}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final java.lang.String getHashed1MD5()
	{
		return (java.lang.String)get(HashItem.hashed1MD5);
	}/**

	 **
	 * Sets a new value for the persistent attribute {@link #hashed1MD5}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final void setHashed1MD5(final java.lang.String hashed1MD5)
	{
		try
		{
			set(HashItem.hashed1MD5,hashed1MD5);
		}
		catch(com.exedio.cope.LengthViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.NotNullViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.ReadOnlyViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.UniqueViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
	}/**

	 **
	 * Returns whether the given value corresponds to the hash in {@link #hashed1}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final boolean checkHashed1(final java.lang.String hashed1)
	{
		return HashItem.hashed1.check(this,hashed1);
	}/**

	 **
	 * Sets a new value for the persistent attribute {@link #hashed1}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final void setHashed1(final java.lang.String hashed1)
	{
		try
		{
			HashItem.hashed1.set(this,hashed1);
		}
		catch(com.exedio.cope.LengthViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.NotNullViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.ReadOnlyViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.UniqueViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
	}/**

	 **
	 * Returns whether the given value corresponds to the hash in {@link #hashed1Latin}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final boolean checkHashed1Latin(final java.lang.String hashed1Latin)
	{
		return HashItem.hashed1Latin.check(this,hashed1Latin);
	}/**

	 **
	 * Sets a new value for the persistent attribute {@link #hashed1Latin}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final void setHashed1Latin(final java.lang.String hashed1Latin)
	{
		try
		{
			HashItem.hashed1Latin.set(this,hashed1Latin);
		}
		catch(com.exedio.cope.LengthViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.NotNullViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.ReadOnlyViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.UniqueViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #hashed2Wrap}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final java.lang.String getHashed2Wrap()
	{
		return (java.lang.String)get(HashItem.hashed2Wrap);
	}/**

	 **
	 * Sets a new value for the persistent attribute {@link #hashed2Wrap}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final void setHashed2Wrap(final java.lang.String hashed2Wrap)
	{
		try
		{
			set(HashItem.hashed2Wrap,hashed2Wrap);
		}
		catch(com.exedio.cope.LengthViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.NotNullViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.ReadOnlyViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.UniqueViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
	}/**

	 **
	 * Returns whether the given value corresponds to the hash in {@link #hashed2}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final boolean checkHashed2(final java.lang.String hashed2)
	{
		return HashItem.hashed2.check(this,hashed2);
	}/**

	 **
	 * Sets a new value for the persistent attribute {@link #hashed2}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final void setHashed2(final java.lang.String hashed2)
	{
		try
		{
			HashItem.hashed2.set(this,hashed2);
		}
		catch(com.exedio.cope.LengthViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.NotNullViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.ReadOnlyViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.UniqueViolationException e)
		{
			throw new com.exedio.cope.NestingRuntimeException(e);
		}
	}/**

	 **
	 * The persistent type information for hashItem.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public static final com.exedio.cope.Type TYPE = 
		new com.exedio.cope.Type(HashItem.class)
;}
