/*
 * Copyright (C) 2004-2005  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.testmodel;

import com.exedio.cope.DataAttribute;
import com.exedio.cope.Item;
import com.exedio.cope.pattern.HttpEntity;

/**
 * @cope.persistent
 * @author Ralf Wiebicke
 */
public class HttpEntityItem extends Item
{

	/**
	 * @cope.setter none
	 */
	public static final DataAttribute fileData = dataAttribute(DEFAULT);
	public static final HttpEntity file = new HttpEntity(DEFAULT, fileData, stringAttribute(DEFAULT), stringAttribute(DEFAULT));

	/**
	 * @cope.setter none
	 */
	public static final DataAttribute imageData = dataAttribute(DEFAULT);
	public static final HttpEntity image = new HttpEntity(DEFAULT, imageData, "image", stringAttribute(DEFAULT));
	
	/**
	 * @cope.setter none
	 */
	public static final DataAttribute photoData = dataAttribute(DEFAULT);
	public static final HttpEntity photo = new HttpEntity(DEFAULT, photoData, "image", "jpeg");
	
/**

	 **
	 * Creates a new HttpEntityItem with all the attributes initially needed.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public HttpEntityItem()
	{
		this(new com.exedio.cope.AttributeValue[]{
		});
	}/**

	 **
	 * Creates a new HttpEntityItem and sets the given attributes initially.
	 * This constructor is called by {@link com.exedio.cope.Type#newItem Type.newItem}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */private HttpEntityItem(final com.exedio.cope.AttributeValue[] initialAttributes)
	{
		super(initialAttributes);
	}/**

	 **
	 * Reactivation constructor. Used for internal purposes only.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 * @see Item#Item(com.exedio.cope.util.ReactivationConstructorDummy,int)
	 *
 */private HttpEntityItem(com.exedio.cope.util.ReactivationConstructorDummy d,final int pk)
	{
		super(d,pk);
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #fileData}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.io.InputStream getFileData()
	{
		return (java.io.InputStream)get(HttpEntityItem.fileData);
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #imageData}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.io.InputStream getImageData()
	{
		return (java.io.InputStream)get(HttpEntityItem.imageData);
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #photoData}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.io.InputStream getPhotoData()
	{
		return (java.io.InputStream)get(HttpEntityItem.photoData);
	}/**

	 **
	 * Returns a URL the data of the data attribute {@link #file} is available under.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.lang.String getFileURL()
	{
		return HttpEntityItem.file.getURL(this);
	}/**

	 **
	 * Returns the major mime type of the data attribute {@link #file}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.lang.String getFileMimeMajor()
	{
		return HttpEntityItem.file.getMimeMajor(this);
	}/**

	 **
	 * Returns the minor mime type of the data attribute {@link #file}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.lang.String getFileMimeMinor()
	{
		return HttpEntityItem.file.getMimeMinor(this);
	}/**

	 **
	 * Sets the new data for the data attribute {@link #file}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 * @throws java.io.IOException if accessing <code>data</code> throws an IOException.
	 *
 */public final void setFile(final java.io.InputStream data,final java.lang.String mimeMajor,final java.lang.String mimeMinor)
			throws
				java.io.IOException
	{
		HttpEntityItem.file.set(this,data,mimeMajor,mimeMinor);
	}/**

	 **
	 * Returns a URL the data of the data attribute {@link #image} is available under.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.lang.String getImageURL()
	{
		return HttpEntityItem.image.getURL(this);
	}/**

	 **
	 * Returns the major mime type of the data attribute {@link #image}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.lang.String getImageMimeMajor()
	{
		return HttpEntityItem.image.getMimeMajor(this);
	}/**

	 **
	 * Returns the minor mime type of the data attribute {@link #image}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.lang.String getImageMimeMinor()
	{
		return HttpEntityItem.image.getMimeMinor(this);
	}/**

	 **
	 * Sets the new data for the data attribute {@link #image}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 * @throws java.io.IOException if accessing <code>data</code> throws an IOException.
	 *
 */public final void setImage(final java.io.InputStream data,final java.lang.String mimeMinor)
			throws
				java.io.IOException
	{
		HttpEntityItem.image.set(this,data,null,mimeMinor);
	}/**

	 **
	 * Returns a URL the data of the data attribute {@link #photo} is available under.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.lang.String getPhotoURL()
	{
		return HttpEntityItem.photo.getURL(this);
	}/**

	 **
	 * Returns the major mime type of the data attribute {@link #photo}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.lang.String getPhotoMimeMajor()
	{
		return HttpEntityItem.photo.getMimeMajor(this);
	}/**

	 **
	 * Returns the minor mime type of the data attribute {@link #photo}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public final java.lang.String getPhotoMimeMinor()
	{
		return HttpEntityItem.photo.getMimeMinor(this);
	}/**

	 **
	 * Sets the new data for the data attribute {@link #photo}.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 * @throws java.io.IOException if accessing <code>data</code> throws an IOException.
	 *
 */public final void setPhoto(final java.io.InputStream data)
			throws
				java.io.IOException
	{
		HttpEntityItem.photo.set(this,data,null,null);
	}/**

	 **
	 * The persistent type information for httpEntityItem.
	 * @cope.generated This method has been generated by the cope instrumentor and will be overwritten by the build process.
	 *
 */public static final com.exedio.cope.Type TYPE =
		new com.exedio.cope.Type(HttpEntityItem.class)
;}
