/*
 * Copyright (C) 2004-2005  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.testmodel;

import com.exedio.cope.lib.IntegerAttribute;
import com.exedio.cope.lib.Item;
import com.exedio.cope.lib.ItemAttribute;
import com.exedio.cope.lib.StringAttribute;
import com.exedio.cope.lib.UniqueConstraint;

/**
 * @persistent
 * @author ralf.wiebicke@exedio.com
 */
public class QualifiedStringQualifier extends Item
{
	public static final ItemAttribute parent = itemAttribute(READ_ONLY_NOT_NULL, QualifiedItem.class);
	
	public static final StringAttribute key = stringAttribute(READ_ONLY_NOT_NULL);
	
	public static final UniqueConstraint qualifyUnique = uniqueConstraint(parent, key);
	
	public static final IntegerAttribute qualifiedA = integerAttribute(DEFAULT);
	public static final IntegerAttribute qualifiedB = integerAttribute(DEFAULT);
	

/**

	 **
	 * Creates a new QualifiedStringQualifier with all the attributes initially needed.
	 * <p><small>Generated by the cope instrumentor.</small>
	 * @param initialParent the initial value for attribute {@link #parent}.
	 * @param initialKey the initial value for attribute {@link #key}.
	 * @throws com.exedio.cope.lib.NotNullViolationException if initialParent, initialKey is null.
	 * @throws com.exedio.cope.lib.UniqueViolationException if initialParent, initialKey is not unique.
	 *
 */public QualifiedStringQualifier(
				final QualifiedItem initialParent,
				final java.lang.String initialKey)
			throws
				com.exedio.cope.lib.NotNullViolationException,
				com.exedio.cope.lib.UniqueViolationException
	{
		this(new com.exedio.cope.lib.AttributeValue[]{
			new com.exedio.cope.lib.AttributeValue(parent,initialParent),
			new com.exedio.cope.lib.AttributeValue(key,initialKey),
		});
		throwInitialNotNullViolationException();
		throwInitialUniqueViolationException();
	}/**

	 **
	 * Creates a new QualifiedStringQualifier and sets the given attributes initially.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */private QualifiedStringQualifier(final com.exedio.cope.lib.AttributeValue[] initialAttributes)
	{
		super(initialAttributes);
	}/**

	 **
	 * Reactivation constructor. Used for internal purposes only.
	 * <p><small>Generated by the cope instrumentor.</small>
	 * @see Item#Item(com.exedio.cope.lib.util.ReactivationConstructorDummy,int)
	 *
 */private QualifiedStringQualifier(com.exedio.cope.lib.util.ReactivationConstructorDummy d,final int pk)
	{
		super(d,pk);
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #parent}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final QualifiedItem getParent()
	{
		return (QualifiedItem)getAttribute(QualifiedStringQualifier.parent);
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #key}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final java.lang.String getKey()
	{
		return (java.lang.String)getAttribute(QualifiedStringQualifier.key);
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #qualifiedA}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final java.lang.Integer getQualifiedA()
	{
		return (java.lang.Integer)getAttribute(QualifiedStringQualifier.qualifiedA);
	}/**

	 **
	 * Sets a new value for the persistent attribute {@link #qualifiedA}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final void setQualifiedA(final java.lang.Integer qualifiedA)
	{
		try
		{
			setAttribute(QualifiedStringQualifier.qualifiedA,qualifiedA);
		}
		catch(com.exedio.cope.lib.LengthViolationException e)
		{
			throw new com.exedio.cope.lib.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.lib.NotNullViolationException e)
		{
			throw new com.exedio.cope.lib.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.lib.ReadOnlyViolationException e)
		{
			throw new com.exedio.cope.lib.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.lib.UniqueViolationException e)
		{
			throw new com.exedio.cope.lib.NestingRuntimeException(e);
		}
	}/**

	 **
	 * Returns the value of the persistent attribute {@link #qualifiedB}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final java.lang.Integer getQualifiedB()
	{
		return (java.lang.Integer)getAttribute(QualifiedStringQualifier.qualifiedB);
	}/**

	 **
	 * Sets a new value for the persistent attribute {@link #qualifiedB}.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public final void setQualifiedB(final java.lang.Integer qualifiedB)
	{
		try
		{
			setAttribute(QualifiedStringQualifier.qualifiedB,qualifiedB);
		}
		catch(com.exedio.cope.lib.LengthViolationException e)
		{
			throw new com.exedio.cope.lib.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.lib.NotNullViolationException e)
		{
			throw new com.exedio.cope.lib.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.lib.ReadOnlyViolationException e)
		{
			throw new com.exedio.cope.lib.NestingRuntimeException(e);
		}
		catch(com.exedio.cope.lib.UniqueViolationException e)
		{
			throw new com.exedio.cope.lib.NestingRuntimeException(e);
		}
	}/**

	 **
	 * Finds a qualifiedStringQualifier by it's unique attributes.
	 * <p><small>Generated by the cope instrumentor.</small>
	 * @param searchedParent shall be equal to attribute {@link #parent}.
	 * @param searchedKey shall be equal to attribute {@link #key}.
	 *
 */public static final QualifiedStringQualifier findByQualifyUnique(final QualifiedItem searchedParent,final java.lang.String searchedKey)
	{
		return (QualifiedStringQualifier)qualifyUnique.searchUnique(new Object[]{searchedParent,searchedKey});
	}/**

	 **
	 * The persistent type information for qualifiedStringQualifier.
	 * <p><small>Generated by the cope instrumentor.</small>
	 *
 */public static final com.exedio.cope.lib.Type TYPE = 
		new com.exedio.cope.lib.Type(QualifiedStringQualifier.class)
;}
