/*
 * Copyright (C) 2004-2006  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;

import java.util.Collection;
import java.util.Date;
import java.util.List;

import com.exedio.cope.DateAttribute;
import com.exedio.cope.Item;
import com.exedio.cope.StringAttribute;

public class AttributeListItem extends Item
{

	public static final AttributeList<String> strings = AttributeList.newList(new StringAttribute(OPTIONAL).lengthRange(4, 8));
	public static final AttributeList<Date> dates = AttributeList.newList(new DateAttribute(MANDATORY));
	
	// TODO SOON generate by instrumentor
	public final List<String> getStrings()
	{
		return strings.get(this);
	}

	// TODO SOON generate by instrumentor
	public final void setStrings(final Collection<? extends String> strings)
	{
		AttributeListItem.strings.set(this, strings);
	}

	// TODO SOON generate by instrumentor
	public final List<Date> getDates()
	{
		return dates.get(this);
	}

	// TODO SOON generate by instrumentor
	public final void setDates(final Collection<? extends Date> dates)
	{
		AttributeListItem.dates.set(this, dates);
	}

	/**

	 **
	 * Creates a new AttributeListItem with all the attributes initially needed.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of attributes.
	 */
	public AttributeListItem()
	{
		this(new com.exedio.cope.SetValue[]{
		});
	}/**

	 **
	 * Creates a new AttributeListItem and sets the given attributes initially.
	 * This constructor is called by {@link com.exedio.cope.Type#newItem Type.newItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	private AttributeListItem(final com.exedio.cope.SetValue[] initialAttributes)
	{
		super(initialAttributes);
	}/**

	 **
	 * Reactivation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.util.ReactivationConstructorDummy,int)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private AttributeListItem(com.exedio.cope.util.ReactivationConstructorDummy d,final int pk)
	{
		super(d,pk);
	}/**

	 **
	 * The persistent type information for attributeListItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	public static final com.exedio.cope.Type<AttributeListItem> TYPE = newType(AttributeListItem.class)
;}
