package com.exedio.cope.pattern;

import com.exedio.cope.Item;
import com.exedio.cope.ItemField;

/**
 * @cope.generic.constructor package
 */
public final class CompositeItemHolder extends Item
{
	public static final ItemField<CompositeOptionalItem> anItem = ItemField.create(CompositeOptionalItem.class);


/**

	 **
	 * Creates a new CompositeItemHolder with all the fields initially needed.
	 * @param anItem the initial value for field {@link #anItem}.
	 * @throws com.exedio.cope.MandatoryViolationException if anItem is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	public CompositeItemHolder(
				final CompositeOptionalItem anItem)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]{
			CompositeItemHolder.anItem.map(anItem),
		});
	}/**

	 **
	 * Creates a new CompositeItemHolder and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	CompositeItemHolder(final com.exedio.cope.SetValue<?>... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Returns the value of {@link #anItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final CompositeOptionalItem getAnItem()
	{
		return CompositeItemHolder.anItem.get(this);
	}/**

	 **
	 * Sets a new value for {@link #anItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final void setAnItem(final CompositeOptionalItem anItem)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		CompositeItemHolder.anItem.set(this,anItem);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for compositeItemHolder.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	public static final com.exedio.cope.Type<CompositeItemHolder> TYPE = com.exedio.cope.TypesBound.newType(CompositeItemHolder.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@SuppressWarnings("unused") private CompositeItemHolder(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
