/*
 * Copyright (C) 2004-2007  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;

import com.exedio.cope.Item;
import com.exedio.cope.StringField;

public class DTypeItem extends Item
{
	static final StringField name = new StringField().toFinal();
	
	static final DynamicModel<DynamicModelLocalizationItem> features = DynamicModel.newModel(newItemField(DynamicModelLocalizationItem.class), 1, 1, 1, 1, 2);
	static final DynamicModel<DynamicModelLocalizationItem> small = DynamicModel.newModel(newItemField(DynamicModelLocalizationItem.class), 1, 0, 0, 0, 0);
	

	/**

	 **
	 * Creates a new DTypeItem with all the fields initially needed.
	 * @param name the initial value for field {@link #name}.
	 * @throws com.exedio.cope.LengthViolationException if name violates its length constraint.
	 * @throws com.exedio.cope.MandatoryViolationException if name is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	DTypeItem(
				final java.lang.String name)
			throws
				com.exedio.cope.LengthViolationException,
				com.exedio.cope.MandatoryViolationException
	{
		this(new com.exedio.cope.SetValue[]{
			DTypeItem.name.map(name),
		});
	}/**

	 **
	 * Creates a new DTypeItem and sets the given fields initially.
	 * This constructor is called by {@link com.exedio.cope.Type#newItem Type.newItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	private DTypeItem(final com.exedio.cope.SetValue... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Reactivation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.util.ReactivationConstructorDummy,int)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@SuppressWarnings("unused") private DTypeItem(final com.exedio.cope.util.ReactivationConstructorDummy d,final int pk)
	{
		super(d,pk);
	}/**

	 **
	 * Returns the value of {@link #name}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getter public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getName()
	{
		return DTypeItem.name.get(this);
	}/**

	 **
	 * Returns the dynamic type of this item in the model {@link #features}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getter public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.pattern.DynamicModel<DynamicModelLocalizationItem>.Type getFeaturesType()
	{
		return DTypeItem.features.getType(this);
	}/**

	 **
	 * Sets the dynamic type of this item in the model {@link #features}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setter public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFeaturesType(final com.exedio.cope.pattern.DynamicModel<DynamicModelLocalizationItem>.Type type)
	{
		DTypeItem.features.setType(this,type);
	}/**

	 **
	 * Returns the value of <tt>field</tt> for this item in the model {@link #features}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getter public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.Object getFeatures(final com.exedio.cope.pattern.DynamicModel<DynamicModelLocalizationItem>.Field field)
	{
		return DTypeItem.features.get(this,field);
	}/**

	 **
	 * Sets the value of <tt>field</tt> for this item in the model {@link #features}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setter public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFeatures(final com.exedio.cope.pattern.DynamicModel<DynamicModelLocalizationItem>.Field field,final java.lang.Object value)
	{
		DTypeItem.features.set(this,field,value);
	}/**

	 **
	 * Returns the dynamic type of this item in the model {@link #small}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getter public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.pattern.DynamicModel<DynamicModelLocalizationItem>.Type getSmallType()
	{
		return DTypeItem.small.getType(this);
	}/**

	 **
	 * Sets the dynamic type of this item in the model {@link #small}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setter public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setSmallType(final com.exedio.cope.pattern.DynamicModel<DynamicModelLocalizationItem>.Type type)
	{
		DTypeItem.small.setType(this,type);
	}/**

	 **
	 * Returns the value of <tt>field</tt> for this item in the model {@link #small}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getter public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.Object getSmall(final com.exedio.cope.pattern.DynamicModel<DynamicModelLocalizationItem>.Field field)
	{
		return DTypeItem.small.get(this,field);
	}/**

	 **
	 * Sets the value of <tt>field</tt> for this item in the model {@link #small}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setter public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setSmall(final com.exedio.cope.pattern.DynamicModel<DynamicModelLocalizationItem>.Field field,final java.lang.Object value)
	{
		DTypeItem.small.set(this,field,value);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for dTypeItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	public static final com.exedio.cope.Type<DTypeItem> TYPE = newType(DTypeItem.class)
;}
