/*
 * Copyright (C) 2004-2012  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;

import com.exedio.cope.AbstractRuntimeTest;
import com.exedio.cope.CopeSchemaName;
import com.exedio.cope.EnumField;
import com.exedio.cope.Item;
import com.exedio.cope.Model;
import com.exedio.cope.StringField;
import com.exedio.cope.pattern.DynamicModel.Enum;
import com.exedio.cope.pattern.DynamicModel.Field;
import com.exedio.cope.pattern.DynamicModel.Type;

public class DynamicModelCastTest extends AbstractRuntimeTest
{
	private static final Model MODEL = new Model(ModelItem.TYPE);

	static
	{
		MODEL.enableSerialization(DynamicModelCastTest.class, "MODEL");
	}

	public DynamicModelCastTest()
	{
		super(MODEL);
	}

	ModelItem item;

	@Override
	public void setUp() throws Exception
	{
		super.setUp();
		item = deleteOnTearDown(new ModelItem("item"));
	}

	public void testIt()
	{
		final Type<Locale> alpha1 = deleteOnTearDown(ModelItem.alpha.createType("alpha1"));
		final Type<Locale> alpha2 = deleteOnTearDown(ModelItem.alpha.createType("alpha2"));
		final Type<Locale> alfax  = deleteOnTearDown(ModelItem.alfa .createType("alfax"));
		final Type<String> betax  = deleteOnTearDown(ModelItem.beta .createType("betax"));
		final Field<Locale> alphaS  = alpha1.addStringField("alphaS");
		final Field<Locale> alpha1a = alpha1.addEnumField("alpha1a");
		final Field<Locale> alpha1b = alpha1.addEnumField("alpha1b");
		final Field<Locale> alpha2x = alpha2.addEnumField("alpha2x");
		final Field<Locale> alfaxx  = alfax .addEnumField("alfaxx");
		final Field<String> betaxx  = betax .addEnumField("betaxx");
		final Enum<Locale> alpha1aEnum = alpha1a.addEnumValue("alpha1a1");

		assertSame(alpha1aEnum, alpha1a.as(alpha1aEnum));
		assertSame(alpha1aEnum, alpha1b.as(alpha1aEnum));
		assertSame(alpha1aEnum, alpha2x.as(alpha1aEnum));
		assertSame(alpha1aEnum, alfaxx .as(alpha1aEnum));

		try
		{
			alphaS.as(alpha1aEnum);
			fail();
		}
		catch(final IllegalArgumentException e)
		{
			assertEquals("operation allowed for getValueType()==ENUM fields only, but was STRING", e.getMessage());
		}

		try
		{
			betaxx.as(alpha1aEnum);
			fail();
		}
		catch(final ClassCastException e)
		{
			assertEquals("expected a java.lang.String, but was a com.exedio.cope.pattern.DynamicModelCastTest$Locale", e.getMessage());
		}
	}

	enum Locale
	{
		ONE, TWO;
	}

	static final class ModelItem extends Item
	{
		static final StringField name = new StringField().toFinal();

		static final DynamicModel<Locale> alpha = DynamicModel.create(EnumField.create(Locale.class), 1, 1, 1, 1, 2);
		@CopeSchemaName("xalfa")
		static final DynamicModel<Locale> alfa  = DynamicModel.create(EnumField.create(Locale.class), 1, 1, 1, 1, 2);
		static final DynamicModel<String> beta  = DynamicModel.create(new StringField(), 1, 1, 1, 1, 2);


	/**

	 **
	 * Creates a new ModelItem with all the fields initially needed.
	 * @param name the initial value for field {@link #name}.
	 * @throws com.exedio.cope.MandatoryViolationException if name is null.
	 * @throws com.exedio.cope.StringLengthViolationException if name violates its length constraint.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	ModelItem(
				final java.lang.String name)
			throws
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.StringLengthViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]{
			ModelItem.name.map(name),
		});
	}/**

	 **
	 * Creates a new ModelItem and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	private ModelItem(final com.exedio.cope.SetValue<?>... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Returns the value of {@link #name}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getName()
	{
		return ModelItem.name.get(this);
	}/**

	 **
	 * Returns the dynamic type of this item in the model {@link #alpha}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getType public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.pattern.DynamicModel.Type<Locale> getAlphaType()
	{
		return ModelItem.alpha.getType(this);
	}/**

	 **
	 * Sets the dynamic type of this item in the model {@link #alpha}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setType public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setAlphaType(final com.exedio.cope.pattern.DynamicModel.Type<Locale> type)
	{
		ModelItem.alpha.setType(this,type);
	}/**

	 **
	 * Returns the value of <tt>field</tt> for this item in the model {@link #alpha}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.Object getAlpha(final com.exedio.cope.pattern.DynamicModel.Field<Locale> field)
	{
		return ModelItem.alpha.get(this,field);
	}/**

	 **
	 * Sets the value of <tt>field</tt> for this item in the model {@link #alpha}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setAlpha(final com.exedio.cope.pattern.DynamicModel.Field<Locale> field,final java.lang.Object value)
	{
		ModelItem.alpha.set(this,field,value);
	}/**

	 **
	 * Returns the dynamic type of this item in the model {@link #alfa}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getType public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.pattern.DynamicModel.Type<Locale> getAlfaType()
	{
		return ModelItem.alfa.getType(this);
	}/**

	 **
	 * Sets the dynamic type of this item in the model {@link #alfa}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setType public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setAlfaType(final com.exedio.cope.pattern.DynamicModel.Type<Locale> type)
	{
		ModelItem.alfa.setType(this,type);
	}/**

	 **
	 * Returns the value of <tt>field</tt> for this item in the model {@link #alfa}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.Object getAlfa(final com.exedio.cope.pattern.DynamicModel.Field<Locale> field)
	{
		return ModelItem.alfa.get(this,field);
	}/**

	 **
	 * Sets the value of <tt>field</tt> for this item in the model {@link #alfa}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setAlfa(final com.exedio.cope.pattern.DynamicModel.Field<Locale> field,final java.lang.Object value)
	{
		ModelItem.alfa.set(this,field,value);
	}/**

	 **
	 * Returns the dynamic type of this item in the model {@link #beta}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getType public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.pattern.DynamicModel.Type<String> getBetaType()
	{
		return ModelItem.beta.getType(this);
	}/**

	 **
	 * Sets the dynamic type of this item in the model {@link #beta}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setType public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setBetaType(final com.exedio.cope.pattern.DynamicModel.Type<String> type)
	{
		ModelItem.beta.setType(this,type);
	}/**

	 **
	 * Returns the value of <tt>field</tt> for this item in the model {@link #beta}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.Object getBeta(final com.exedio.cope.pattern.DynamicModel.Field<String> field)
	{
		return ModelItem.beta.get(this,field);
	}/**

	 **
	 * Sets the value of <tt>field</tt> for this item in the model {@link #beta}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setBeta(final com.exedio.cope.pattern.DynamicModel.Field<String> field,final java.lang.Object value)
	{
		ModelItem.beta.set(this,field,value);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for modelItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	static final com.exedio.cope.Type<ModelItem> TYPE = com.exedio.cope.TypesBound.newType(ModelItem.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@SuppressWarnings("unused") private ModelItem(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
}
