/*
 * Copyright (C) 2004-2015  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;
import com.exedio.cope.Item;
import com.exedio.cope.SetValue;
import com.exedio.cope.StringField;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
// EnumMapFieldItem.Language has to be used with full name below, otherwise instrumentation fails on Windows:
// import com.exedio.cope.pattern.EnumMapFieldItem.Language;

public final class EnumMapFieldFinalItem extends Item
{
	static final EnumMapField<EnumMapFieldItem.Language, String> text =
			EnumMapField.create(EnumMapFieldItem.Language.class, new StringField().toFinal().optional());

	EnumMapFieldFinalItem()
	{
		this(SetValue.EMPTY_ARRAY);
	}

	// must not be generated by instrumentor
	@SuppressWarnings("UnusedReturnValue")
	String getTextWithFallback(final EnumMapFieldItem.Language k)
	{
		return text.getWithFallback(this,k);
	}

	// must not be generated by instrumentor
	void setText(
			@Nonnull final EnumMapFieldItem.Language k,
			@Nullable final String text)
	{
		EnumMapFieldFinalItem.text.set(this, k, text);
	}

	// must not be generated by instrumentor
	@SuppressWarnings("UnusedReturnValue")
	java.util.Map<EnumMapFieldItem.Language,String> getTextMapWithFallback()
	{
		return text.getMapWithFallback(this);
	}

	// must not be generated by instrumentor
	void setTextMap(@Nonnull final Map<EnumMapFieldItem.Language,String> text)
	{
		EnumMapFieldFinalItem.text.setMap(this, text);
	}

	/**
	 * Creates a new EnumMapFieldFinalItem with all the fields initially needed.
	 * @param text the initial value for field {@link #text}.
	 * @throws com.exedio.cope.StringLengthViolationException if text violates its length constraint.
	 */
	@com.exedio.cope.instrument.Generated // customize with @WrapperType(constructor=...) and @WrapperInitial
	@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedInnerClassAccess"})
	EnumMapFieldFinalItem(
				@javax.annotation.Nonnull final java.util.EnumMap<EnumMapFieldItem.Language,String> text)
			throws
				com.exedio.cope.StringLengthViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]{
			EnumMapFieldFinalItem.text.map(text),
		});
	}

	/**
	 * Creates a new EnumMapFieldFinalItem and sets the given fields initially.
	 */
	@com.exedio.cope.instrument.Generated // customize with @WrapperType(genericConstructor=...)
	private EnumMapFieldFinalItem(final com.exedio.cope.SetValue<?>... setValues){super(setValues);}

	/**
	 * Returns the value mapped to {@code k} by the field map {@link #text}.
	 */
	@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="get")
	@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
	@javax.annotation.Nullable
	String getText(@javax.annotation.Nonnull final EnumMapFieldItem.Language k)
	{
		return EnumMapFieldFinalItem.text.get(this,k);
	}

	@com.exedio.cope.instrument.Generated // customize with @Wrapper(wrap="getMap")
	@java.lang.SuppressWarnings({"RedundantSuppression","TypeParameterExtendsFinalClass","UnnecessarilyQualifiedStaticUsage"})
	@javax.annotation.Nonnull
	java.util.Map<EnumMapFieldItem.Language,String> getTextMap()
	{
		return EnumMapFieldFinalItem.text.getMap(this);
	}

	@com.exedio.cope.instrument.Generated
	private static final long serialVersionUID = 1l;

	/**
	 * The persistent type information for enumMapFieldFinalItem.
	 */
	@com.exedio.cope.instrument.Generated // customize with @WrapperType(type=...)
	public static final com.exedio.cope.Type<EnumMapFieldFinalItem> TYPE = com.exedio.cope.TypesBound.newType(EnumMapFieldFinalItem.class);

	/**
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 */
	@com.exedio.cope.instrument.Generated
	private EnumMapFieldFinalItem(final com.exedio.cope.ActivationParameters ap){super(ap);}
}
