/*
 * Copyright (C) 2004-2009  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;

import com.exedio.cope.Item;
import com.exedio.cope.StringField;

class ImporterItem extends Item
{
	static final StringField code = new StringField().toFinal().unique();
	/**
	 * Problem disapears when Importer becomes public
	 * @cope.ignore
	 */
	static final Importer<String> byCode = Importer.newImporter(code);
	static final StringField description = new StringField();
	static final StringField description2 = new StringField();
	
	/**

	 **
	 * Import {@link #byCode}.
	 * @return the imported item
	 */
	static final ImporterItem importByCode(final java.lang.String keyValue,final com.exedio.cope.SetValue[] setValues)
	{
		return ImporterItem.byCode.doImport(ImporterItem.class,keyValue,setValues);
	}/**

	 **
	 * Creates a new ImporterItem with all the fields initially needed.
	 * @param code the initial value for field {@link #code}.
	 * @param description the initial value for field {@link #description}.
	 * @param description2 the initial value for field {@link #description2}.
	 * @throws com.exedio.cope.MandatoryViolationException if code, description, description2 is null.
	 * @throws com.exedio.cope.StringLengthViolationException if code, description, description2 violates its length constraint.
	 * @throws com.exedio.cope.UniqueViolationException if code is not unique.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	ImporterItem(
				final java.lang.String code,
				final java.lang.String description,
				final java.lang.String description2)
			throws
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.StringLengthViolationException,
				com.exedio.cope.UniqueViolationException
	{
		this(new com.exedio.cope.SetValue[]{
			ImporterItem.code.map(code),
			ImporterItem.description.map(description),
			ImporterItem.description2.map(description2),
		});
	}/**

	 **
	 * Creates a new ImporterItem and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	private ImporterItem(final com.exedio.cope.SetValue... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@SuppressWarnings("unused") private ImporterItem(final com.exedio.cope.ActivationParameters ap)
	{
		super(ap);
	}/**

	 **
	 * Returns the value of {@link #code}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getCode()
	{
		return ImporterItem.code.get(this);
	}/**

	 **
	 * Finds a importerItem by it's {@link #code}.
	 * @param code shall be equal to field {@link #code}.
	 * @return null if there is no matching item.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.for public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	static final ImporterItem forCode(final java.lang.String code)
	{
		return ImporterItem.code.searchUnique(ImporterItem.class,code);
	}/**

	 **
	 * Finds a importerItem by it's {@link #code}.
	 * @deprecated use for{@link #code} instead.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.findBy public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@Deprecated
	static final ImporterItem findByCode(final java.lang.String code)
	{
		return ImporterItem.code.searchUnique(ImporterItem.class,code);
	}/**

	 **
	 * Returns the value of {@link #description}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getDescription()
	{
		return ImporterItem.description.get(this);
	}/**

	 **
	 * Sets a new value for {@link #description}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setDescription(final java.lang.String description)
			throws
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.StringLengthViolationException
	{
		ImporterItem.description.set(this,description);
	}/**

	 **
	 * Returns the value of {@link #description2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getDescription2()
	{
		return ImporterItem.description2.get(this);
	}/**

	 **
	 * Sets a new value for {@link #description2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setDescription2(final java.lang.String description2)
			throws
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.StringLengthViolationException
	{
		ImporterItem.description2.set(this,description2);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for importerItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	static final com.exedio.cope.Type<ImporterItem> TYPE = com.exedio.cope.TypesBound.newType(ImporterItem.class)
;}
