/*
 * Copyright (C) 2004-2015  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;

import com.exedio.cope.Item;

final class InterfaceItemFieldItem extends Item
{
	/**
	 * @cope.ignore
	 */
	@SuppressWarnings(
	{"unchecked", "rawtypes"})
	static final InterfaceItemField<InterfaceItemFieldItemInterface> field = InterfaceItemField.create(
			InterfaceItemFieldItemInterface.class, new Class[]
			{InterfaceItemFieldItemInterfaceImplementationA.class, InterfaceItemFieldItemInterfaceImplementationB.class});

	/**
	 * @cope.ignore
	 */
	@SuppressWarnings(
	{"unchecked", "rawtypes"})
	static final InterfaceItemField<InterfaceItemFieldItemInterface> optionalField = InterfaceItemField.create(
			InterfaceItemFieldItemInterface.class, new Class[]
			{InterfaceItemFieldItemInterfaceImplementationA.class, InterfaceItemFieldItemInterfaceImplementationB.class})
			.optional();

	InterfaceItemFieldItem(final InterfaceItemFieldItemInterface field)
			throws com.exedio.cope.MandatoryViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]
		{
				InterfaceItemFieldItem.field.map(field),
		});
	}

	InterfaceItemFieldItemInterface getField()
	{
		return field.get(this);
	}

	void setField(final InterfaceItemFieldItemInterface value)
	{
		this.set(InterfaceItemFieldItem.field.map(value));
	}

	InterfaceItemFieldItemInterface getOptionalField()
	{
		return optionalField.get(this);
	}

	void setOptionalField(final InterfaceItemFieldItemInterface value)
	{
		this.set(InterfaceItemFieldItem.optionalField.map(value));
	}


	/**

	 **
	 * Creates a new InterfaceItemFieldItem with all the fields initially needed.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	InterfaceItemFieldItem()
	{
		this(new com.exedio.cope.SetValue<?>[]{
		});
	}/**

	 **
	 * Creates a new InterfaceItemFieldItem and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private InterfaceItemFieldItem(final com.exedio.cope.SetValue<?>... setValues)
	{
		super(setValues);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for interfaceItemFieldItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final com.exedio.cope.Type<InterfaceItemFieldItem> TYPE = com.exedio.cope.TypesBound.newType(InterfaceItemFieldItem.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@SuppressWarnings("unused") private InterfaceItemFieldItem(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
