/*
 * Copyright (C) 2004-2009  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;

import java.util.Date;

import com.exedio.cope.DateField;
import com.exedio.cope.IntegerField;
import com.exedio.cope.Item;
import com.exedio.cope.StringField;

/**
 * @cope.generic.constructor package
 */
public class LimitedListFieldItem extends Item
{
	// explicit external source

	static final IntegerField num1 = new IntegerField().optional();

	static final IntegerField num2 = new IntegerField().optional();

	static final IntegerField num3 = new IntegerField().optional();
	
	static final LimitedListField<Integer> nums = LimitedListField.newList(num1, num2, num3);

	// implicit external source

	static final LimitedListField<Date> dates = LimitedListField.newList(new DateField().optional(), new DateField().optional());

	// internal source

	static final LimitedListField<String> strings = LimitedListField.newList(new StringField().optional().lengthRange(1, 11), 4);

	LimitedListFieldItem(final int initialNum1, final int initialNum2, final int initialNum3)
	{
		super(
			num1.map(initialNum1),
			num2.map(initialNum2),
			num3.map(initialNum3));
	}

/**

	 **
	 * Creates a new LimitedListFieldItem with all the fields initially needed.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	public LimitedListFieldItem()
	{
		this(new com.exedio.cope.SetValue[]{
		});
	}/**

	 **
	 * Creates a new LimitedListFieldItem and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	LimitedListFieldItem(final com.exedio.cope.SetValue... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@SuppressWarnings("unused") private LimitedListFieldItem(final com.exedio.cope.ActivationParameters ap)
	{
		super(ap);
	}/**

	 **
	 * Returns the value of {@link #num1}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.Integer getNum1()
	{
		return LimitedListFieldItem.num1.get(this);
	}/**

	 **
	 * Sets a new value for {@link #num1}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setNum1(final java.lang.Integer num1)
	{
		LimitedListFieldItem.num1.set(this,num1);
	}/**

	 **
	 * Returns the value of {@link #num2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.Integer getNum2()
	{
		return LimitedListFieldItem.num2.get(this);
	}/**

	 **
	 * Sets a new value for {@link #num2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setNum2(final java.lang.Integer num2)
	{
		LimitedListFieldItem.num2.set(this,num2);
	}/**

	 **
	 * Returns the value of {@link #num3}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.Integer getNum3()
	{
		return LimitedListFieldItem.num3.get(this);
	}/**

	 **
	 * Sets a new value for {@link #num3}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setNum3(final java.lang.Integer num3)
	{
		LimitedListFieldItem.num3.set(this,num3);
	}/**

	 **
	 * Returns the value of {@link #nums}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.util.List<Integer> getNums()
	{
		return LimitedListFieldItem.nums.get(this);
	}/**

	 **
	 * Sets a new value for {@link #nums}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setNums(final java.util.Collection<? extends Integer> nums)
			throws
				java.lang.ClassCastException
	{
		LimitedListFieldItem.nums.set(this,nums);
	}/**

	 **
	 * Returns the value of {@link #dates}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.util.List<Date> getDates()
	{
		return LimitedListFieldItem.dates.get(this);
	}/**

	 **
	 * Sets a new value for {@link #dates}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setDates(final java.util.Collection<? extends Date> dates)
			throws
				java.lang.ClassCastException
	{
		LimitedListFieldItem.dates.set(this,dates);
	}/**

	 **
	 * Returns the value of {@link #strings}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.util.List<String> getStrings()
	{
		return LimitedListFieldItem.strings.get(this);
	}/**

	 **
	 * Sets a new value for {@link #strings}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setStrings(final java.util.Collection<? extends String> strings)
			throws
				com.exedio.cope.StringLengthViolationException,
				java.lang.ClassCastException
	{
		LimitedListFieldItem.strings.set(this,strings);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for limitedListFieldItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	public static final com.exedio.cope.Type<LimitedListFieldItem> TYPE = com.exedio.cope.TypesBound.newType(LimitedListFieldItem.class)
;}
