/*
 * Copyright (C) 2004-2012  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;

import com.exedio.cope.CopeSchemaName;
import com.exedio.cope.Item;
import com.exedio.cope.StringField;

public final class MediaUrlItem extends Item implements MediaUrlCatchphraseProvider
{
	/**
	 * @cope.initial
	 */
	@CopeSchemaName("phrase")
	static final StringField catchphrase = new StringField().optional();


	static final Media foto = new Media().optional().lengthMax(2000).contentType("image/jpeg");

	@PreventUrlGuessing()
	static final Media fotoSecure = new Media().optional().lengthMax(2000).contentType("image/jpeg");


	static final Media file = new Media().optional().lengthMax(2000).contentType("foo/bar");

	@PreventUrlGuessing()
	static final Media fileSecure = new Media().optional().lengthMax(2000).contentType("foo/bar");


	public String getMediaUrlCatchphrase(final MediaPath path)
	{
		return getCatchphrase();
	}


	/**

	 **
	 * Creates a new MediaUrlItem with all the fields initially needed.
	 * @param catchphrase the initial value for field {@link #catchphrase}.
	 * @throws com.exedio.cope.StringLengthViolationException if catchphrase violates its length constraint.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	MediaUrlItem(
				final java.lang.String catchphrase)
			throws
				com.exedio.cope.StringLengthViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]{
			MediaUrlItem.catchphrase.map(catchphrase),
		});
	}/**

	 **
	 * Creates a new MediaUrlItem and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	private MediaUrlItem(final com.exedio.cope.SetValue<?>... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Returns the value of {@link #catchphrase}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getCatchphrase()
	{
		return MediaUrlItem.catchphrase.get(this);
	}/**

	 **
	 * Sets a new value for {@link #catchphrase}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setCatchphrase(final java.lang.String catchphrase)
			throws
				com.exedio.cope.StringLengthViolationException
	{
		MediaUrlItem.catchphrase.set(this,catchphrase);
	}/**

	 **
	 * Returns a URL the content of {@link #foto} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getURL public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getFotoNameURL()
	{
		return MediaUrlItem.foto.getURL(this);
	}/**

	 **
	 * Returns a Locator the content of {@link #foto} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLocator public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.pattern.MediaPath.Locator getFotoNameLocator()
	{
		return MediaUrlItem.foto.getLocator(this);
	}/**

	 **
	 * Returns whether media {@link #foto} is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isNull public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final boolean isFotoNameNull()
	{
		return MediaUrlItem.foto.isNull(this);
	}/**

	 **
	 * Returns the last modification date of media {@link #foto}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLastModified public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.util.Date getFotoNameLastModified()
	{
		return MediaUrlItem.foto.getLastModified(this);
	}/**

	 **
	 * Returns the body length of the media {@link #foto}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLength public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final long getFotoNameLength()
	{
		return MediaUrlItem.foto.getLength(this);
	}/**

	 **
	 * Returns the body of the media {@link #foto}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final byte[] getFotoNameBody()
	{
		return MediaUrlItem.foto.getBody(this);
	}/**

	 **
	 * Writes the body of media {@link #foto} into the given stream.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void getFotoNameBody(final java.io.OutputStream body)
			throws
				java.io.IOException
	{
		MediaUrlItem.foto.getBody(this,body);
	}/**

	 **
	 * Writes the body of media {@link #foto} into the given file.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void getFotoNameBody(final java.io.File body)
			throws
				java.io.IOException
	{
		MediaUrlItem.foto.getBody(this,body);
	}/**

	 **
	 * Sets the content of media {@link #foto}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFotoName(final com.exedio.cope.pattern.Media.Value fotoName)
			throws
				java.io.IOException
	{
		MediaUrlItem.foto.set(this,fotoName);
	}/**

	 **
	 * Sets the content of media {@link #foto}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFotoName(final byte[] body,final java.lang.String contentType)
	{
		MediaUrlItem.foto.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #foto}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFotoName(final java.io.InputStream body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.foto.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #foto}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFotoName(final java.io.File body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.foto.set(this,body,contentType);
	}/**

	 **
	 * Returns a URL the content of {@link #fotoSecure} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getURL public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getFotoNameSecureURL()
	{
		return MediaUrlItem.fotoSecure.getURL(this);
	}/**

	 **
	 * Returns a Locator the content of {@link #fotoSecure} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLocator public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.pattern.MediaPath.Locator getFotoNameSecureLocator()
	{
		return MediaUrlItem.fotoSecure.getLocator(this);
	}/**

	 **
	 * Returns whether media {@link #fotoSecure} is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isNull public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final boolean isFotoNameSecureNull()
	{
		return MediaUrlItem.fotoSecure.isNull(this);
	}/**

	 **
	 * Returns the last modification date of media {@link #fotoSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLastModified public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.util.Date getFotoNameSecureLastModified()
	{
		return MediaUrlItem.fotoSecure.getLastModified(this);
	}/**

	 **
	 * Returns the body length of the media {@link #fotoSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLength public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final long getFotoNameSecureLength()
	{
		return MediaUrlItem.fotoSecure.getLength(this);
	}/**

	 **
	 * Returns the body of the media {@link #fotoSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final byte[] getFotoNameSecureBody()
	{
		return MediaUrlItem.fotoSecure.getBody(this);
	}/**

	 **
	 * Writes the body of media {@link #fotoSecure} into the given stream.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void getFotoNameSecureBody(final java.io.OutputStream body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoSecure.getBody(this,body);
	}/**

	 **
	 * Writes the body of media {@link #fotoSecure} into the given file.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void getFotoNameSecureBody(final java.io.File body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoSecure.getBody(this,body);
	}/**

	 **
	 * Sets the content of media {@link #fotoSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFotoNameSecure(final com.exedio.cope.pattern.Media.Value fotoNameSecure)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoSecure.set(this,fotoNameSecure);
	}/**

	 **
	 * Sets the content of media {@link #fotoSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFotoNameSecure(final byte[] body,final java.lang.String contentType)
	{
		MediaUrlItem.fotoSecure.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fotoSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFotoNameSecure(final java.io.InputStream body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoSecure.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fotoSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFotoNameSecure(final java.io.File body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoSecure.set(this,body,contentType);
	}/**

	 **
	 * Returns a URL the content of {@link #file} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getURL public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getFileNameURL()
	{
		return MediaUrlItem.file.getURL(this);
	}/**

	 **
	 * Returns a Locator the content of {@link #file} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLocator public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.pattern.MediaPath.Locator getFileNameLocator()
	{
		return MediaUrlItem.file.getLocator(this);
	}/**

	 **
	 * Returns whether media {@link #file} is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isNull public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final boolean isFileNameNull()
	{
		return MediaUrlItem.file.isNull(this);
	}/**

	 **
	 * Returns the last modification date of media {@link #file}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLastModified public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.util.Date getFileNameLastModified()
	{
		return MediaUrlItem.file.getLastModified(this);
	}/**

	 **
	 * Returns the body length of the media {@link #file}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLength public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final long getFileNameLength()
	{
		return MediaUrlItem.file.getLength(this);
	}/**

	 **
	 * Returns the body of the media {@link #file}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final byte[] getFileNameBody()
	{
		return MediaUrlItem.file.getBody(this);
	}/**

	 **
	 * Writes the body of media {@link #file} into the given stream.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void getFileNameBody(final java.io.OutputStream body)
			throws
				java.io.IOException
	{
		MediaUrlItem.file.getBody(this,body);
	}/**

	 **
	 * Writes the body of media {@link #file} into the given file.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void getFileNameBody(final java.io.File body)
			throws
				java.io.IOException
	{
		MediaUrlItem.file.getBody(this,body);
	}/**

	 **
	 * Sets the content of media {@link #file}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFileName(final com.exedio.cope.pattern.Media.Value fileName)
			throws
				java.io.IOException
	{
		MediaUrlItem.file.set(this,fileName);
	}/**

	 **
	 * Sets the content of media {@link #file}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFileName(final byte[] body,final java.lang.String contentType)
	{
		MediaUrlItem.file.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #file}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFileName(final java.io.InputStream body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.file.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #file}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFileName(final java.io.File body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.file.set(this,body,contentType);
	}/**

	 **
	 * Returns a URL the content of {@link #fileSecure} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getURL public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getFileNameSecureURL()
	{
		return MediaUrlItem.fileSecure.getURL(this);
	}/**

	 **
	 * Returns a Locator the content of {@link #fileSecure} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLocator public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final com.exedio.cope.pattern.MediaPath.Locator getFileNameSecureLocator()
	{
		return MediaUrlItem.fileSecure.getLocator(this);
	}/**

	 **
	 * Returns whether media {@link #fileSecure} is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isNull public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final boolean isFileNameSecureNull()
	{
		return MediaUrlItem.fileSecure.isNull(this);
	}/**

	 **
	 * Returns the last modification date of media {@link #fileSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLastModified public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.util.Date getFileNameSecureLastModified()
	{
		return MediaUrlItem.fileSecure.getLastModified(this);
	}/**

	 **
	 * Returns the body length of the media {@link #fileSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLength public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final long getFileNameSecureLength()
	{
		return MediaUrlItem.fileSecure.getLength(this);
	}/**

	 **
	 * Returns the body of the media {@link #fileSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final byte[] getFileNameSecureBody()
	{
		return MediaUrlItem.fileSecure.getBody(this);
	}/**

	 **
	 * Writes the body of media {@link #fileSecure} into the given stream.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void getFileNameSecureBody(final java.io.OutputStream body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileSecure.getBody(this,body);
	}/**

	 **
	 * Writes the body of media {@link #fileSecure} into the given file.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void getFileNameSecureBody(final java.io.File body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileSecure.getBody(this,body);
	}/**

	 **
	 * Sets the content of media {@link #fileSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFileNameSecure(final com.exedio.cope.pattern.Media.Value fileNameSecure)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileSecure.set(this,fileNameSecure);
	}/**

	 **
	 * Sets the content of media {@link #fileSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFileNameSecure(final byte[] body,final java.lang.String contentType)
	{
		MediaUrlItem.fileSecure.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fileSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFileNameSecure(final java.io.InputStream body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileSecure.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fileSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setFileNameSecure(final java.io.File body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileSecure.set(this,body,contentType);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for mediaUrlItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	public static final com.exedio.cope.Type<MediaUrlItem> TYPE = com.exedio.cope.TypesBound.newType(MediaUrlItem.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@SuppressWarnings("unused") private MediaUrlItem(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
