/*
 * Copyright (C) 2004-2012  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;

import com.exedio.cope.CopeSchemaName;
import com.exedio.cope.Item;
import com.exedio.cope.StringField;

public final class MediaUrlItem extends Item implements MediaUrlCatchphraseProvider
{
	/**
	 * @cope.initial
	 */
	@CopeSchemaName("phrase")
	static final StringField catchphrase = new StringField().optional();


	/** @cope.getURL none */
	static final Media foto = new Media().optional().lengthMax(2000).contentType("image/jpeg");

	/** @cope.getURL none */
	@PreventUrlGuessing()
	static final Media fotoSecure = new Media().optional().lengthMax(2000).contentType("image/jpeg");

	/** @cope.getURL none */
	@UrlFingerPrinting()
	static final Media fotoFinger = new Media().optional().lengthMax(2000).contentType("image/jpeg");

	/** @cope.getURL none */
	static final Media file = new Media().optional().lengthMax(2000).contentType("foo/bar");

	/** @cope.getURL none */
	@PreventUrlGuessing()
	static final Media fileSecure = new Media().optional().lengthMax(2000).contentType("foo/bar");

	/** @cope.getURL none */
	@UrlFingerPrinting()
	static final Media fileFinger = new Media().optional().lengthMax(2000).contentType("foo/bar");


	public String getMediaUrlCatchphrase(final MediaPath path)
	{
		return getCatchphrase();
	}


	/**

	 **
	 * Creates a new MediaUrlItem with all the fields initially needed.
	 * @param catchphrase the initial value for field {@link #catchphrase}.
	 * @throws com.exedio.cope.StringLengthViolationException if catchphrase violates its length constraint.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	MediaUrlItem(
				final java.lang.String catchphrase)
			throws
				com.exedio.cope.StringLengthViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]{
			MediaUrlItem.catchphrase.map(catchphrase),
		});
	}/**

	 **
	 * Creates a new MediaUrlItem and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private MediaUrlItem(final com.exedio.cope.SetValue<?>... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Returns the value of {@link #catchphrase}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final java.lang.String getCatchphrase()
	{
		return MediaUrlItem.catchphrase.get(this);
	}/**

	 **
	 * Sets a new value for {@link #catchphrase}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setCatchphrase(final java.lang.String catchphrase)
			throws
				com.exedio.cope.StringLengthViolationException
	{
		MediaUrlItem.catchphrase.set(this,catchphrase);
	}/**

	 **
	 * Returns a Locator the content of {@link #foto} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLocator public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final com.exedio.cope.pattern.MediaPath.Locator getFotoLocator()
	{
		return MediaUrlItem.foto.getLocator(this);
	}/**

	 **
	 * Returns whether media {@link #foto} is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isNull public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean isFotoNull()
	{
		return MediaUrlItem.foto.isNull(this);
	}/**

	 **
	 * Returns the last modification date of media {@link #foto}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLastModified public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final java.util.Date getFotoLastModified()
	{
		return MediaUrlItem.foto.getLastModified(this);
	}/**

	 **
	 * Returns the body length of the media {@link #foto}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLength public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final long getFotoLength()
	{
		return MediaUrlItem.foto.getLength(this);
	}/**

	 **
	 * Returns the body of the media {@link #foto}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final byte[] getFotoBody()
	{
		return MediaUrlItem.foto.getBody(this);
	}/**

	 **
	 * Writes the body of media {@link #foto} into the given stream.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFotoBody(final java.io.OutputStream body)
			throws
				java.io.IOException
	{
		MediaUrlItem.foto.getBody(this,body);
	}/**

	 **
	 * Writes the body of media {@link #foto} into the given file.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFotoBody(final java.io.File body)
			throws
				java.io.IOException
	{
		MediaUrlItem.foto.getBody(this,body);
	}/**

	 **
	 * Sets the content of media {@link #foto}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFoto(final com.exedio.cope.pattern.Media.Value foto)
			throws
				java.io.IOException
	{
		MediaUrlItem.foto.set(this,foto);
	}/**

	 **
	 * Sets the content of media {@link #foto}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFoto(final byte[] body,final java.lang.String contentType)
	{
		MediaUrlItem.foto.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #foto}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFoto(final java.io.InputStream body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.foto.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #foto}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFoto(final java.io.File body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.foto.set(this,body,contentType);
	}/**

	 **
	 * Returns a Locator the content of {@link #fotoSecure} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLocator public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final com.exedio.cope.pattern.MediaPath.Locator getFotoSecureLocator()
	{
		return MediaUrlItem.fotoSecure.getLocator(this);
	}/**

	 **
	 * Returns whether media {@link #fotoSecure} is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isNull public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean isFotoSecureNull()
	{
		return MediaUrlItem.fotoSecure.isNull(this);
	}/**

	 **
	 * Returns the last modification date of media {@link #fotoSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLastModified public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final java.util.Date getFotoSecureLastModified()
	{
		return MediaUrlItem.fotoSecure.getLastModified(this);
	}/**

	 **
	 * Returns the body length of the media {@link #fotoSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLength public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final long getFotoSecureLength()
	{
		return MediaUrlItem.fotoSecure.getLength(this);
	}/**

	 **
	 * Returns the body of the media {@link #fotoSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final byte[] getFotoSecureBody()
	{
		return MediaUrlItem.fotoSecure.getBody(this);
	}/**

	 **
	 * Writes the body of media {@link #fotoSecure} into the given stream.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFotoSecureBody(final java.io.OutputStream body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoSecure.getBody(this,body);
	}/**

	 **
	 * Writes the body of media {@link #fotoSecure} into the given file.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFotoSecureBody(final java.io.File body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoSecure.getBody(this,body);
	}/**

	 **
	 * Sets the content of media {@link #fotoSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFotoSecure(final com.exedio.cope.pattern.Media.Value fotoSecure)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoSecure.set(this,fotoSecure);
	}/**

	 **
	 * Sets the content of media {@link #fotoSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFotoSecure(final byte[] body,final java.lang.String contentType)
	{
		MediaUrlItem.fotoSecure.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fotoSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFotoSecure(final java.io.InputStream body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoSecure.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fotoSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFotoSecure(final java.io.File body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoSecure.set(this,body,contentType);
	}/**

	 **
	 * Returns a Locator the content of {@link #fotoFinger} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLocator public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final com.exedio.cope.pattern.MediaPath.Locator getFotoFingerLocator()
	{
		return MediaUrlItem.fotoFinger.getLocator(this);
	}/**

	 **
	 * Returns whether media {@link #fotoFinger} is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isNull public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean isFotoFingerNull()
	{
		return MediaUrlItem.fotoFinger.isNull(this);
	}/**

	 **
	 * Returns the last modification date of media {@link #fotoFinger}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLastModified public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final java.util.Date getFotoFingerLastModified()
	{
		return MediaUrlItem.fotoFinger.getLastModified(this);
	}/**

	 **
	 * Returns the body length of the media {@link #fotoFinger}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLength public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final long getFotoFingerLength()
	{
		return MediaUrlItem.fotoFinger.getLength(this);
	}/**

	 **
	 * Returns the body of the media {@link #fotoFinger}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final byte[] getFotoFingerBody()
	{
		return MediaUrlItem.fotoFinger.getBody(this);
	}/**

	 **
	 * Writes the body of media {@link #fotoFinger} into the given stream.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFotoFingerBody(final java.io.OutputStream body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoFinger.getBody(this,body);
	}/**

	 **
	 * Writes the body of media {@link #fotoFinger} into the given file.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFotoFingerBody(final java.io.File body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoFinger.getBody(this,body);
	}/**

	 **
	 * Sets the content of media {@link #fotoFinger}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFotoFinger(final com.exedio.cope.pattern.Media.Value fotoFinger)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoFinger.set(this,fotoFinger);
	}/**

	 **
	 * Sets the content of media {@link #fotoFinger}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFotoFinger(final byte[] body,final java.lang.String contentType)
	{
		MediaUrlItem.fotoFinger.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fotoFinger}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFotoFinger(final java.io.InputStream body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoFinger.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fotoFinger}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFotoFinger(final java.io.File body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fotoFinger.set(this,body,contentType);
	}/**

	 **
	 * Returns a Locator the content of {@link #file} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLocator public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final com.exedio.cope.pattern.MediaPath.Locator getFileLocator()
	{
		return MediaUrlItem.file.getLocator(this);
	}/**

	 **
	 * Returns whether media {@link #file} is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isNull public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean isFileNull()
	{
		return MediaUrlItem.file.isNull(this);
	}/**

	 **
	 * Returns the last modification date of media {@link #file}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLastModified public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final java.util.Date getFileLastModified()
	{
		return MediaUrlItem.file.getLastModified(this);
	}/**

	 **
	 * Returns the body length of the media {@link #file}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLength public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final long getFileLength()
	{
		return MediaUrlItem.file.getLength(this);
	}/**

	 **
	 * Returns the body of the media {@link #file}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final byte[] getFileBody()
	{
		return MediaUrlItem.file.getBody(this);
	}/**

	 **
	 * Writes the body of media {@link #file} into the given stream.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFileBody(final java.io.OutputStream body)
			throws
				java.io.IOException
	{
		MediaUrlItem.file.getBody(this,body);
	}/**

	 **
	 * Writes the body of media {@link #file} into the given file.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFileBody(final java.io.File body)
			throws
				java.io.IOException
	{
		MediaUrlItem.file.getBody(this,body);
	}/**

	 **
	 * Sets the content of media {@link #file}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFile(final com.exedio.cope.pattern.Media.Value file)
			throws
				java.io.IOException
	{
		MediaUrlItem.file.set(this,file);
	}/**

	 **
	 * Sets the content of media {@link #file}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFile(final byte[] body,final java.lang.String contentType)
	{
		MediaUrlItem.file.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #file}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFile(final java.io.InputStream body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.file.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #file}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFile(final java.io.File body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.file.set(this,body,contentType);
	}/**

	 **
	 * Returns a Locator the content of {@link #fileSecure} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLocator public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final com.exedio.cope.pattern.MediaPath.Locator getFileSecureLocator()
	{
		return MediaUrlItem.fileSecure.getLocator(this);
	}/**

	 **
	 * Returns whether media {@link #fileSecure} is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isNull public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean isFileSecureNull()
	{
		return MediaUrlItem.fileSecure.isNull(this);
	}/**

	 **
	 * Returns the last modification date of media {@link #fileSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLastModified public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final java.util.Date getFileSecureLastModified()
	{
		return MediaUrlItem.fileSecure.getLastModified(this);
	}/**

	 **
	 * Returns the body length of the media {@link #fileSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLength public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final long getFileSecureLength()
	{
		return MediaUrlItem.fileSecure.getLength(this);
	}/**

	 **
	 * Returns the body of the media {@link #fileSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final byte[] getFileSecureBody()
	{
		return MediaUrlItem.fileSecure.getBody(this);
	}/**

	 **
	 * Writes the body of media {@link #fileSecure} into the given stream.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFileSecureBody(final java.io.OutputStream body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileSecure.getBody(this,body);
	}/**

	 **
	 * Writes the body of media {@link #fileSecure} into the given file.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFileSecureBody(final java.io.File body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileSecure.getBody(this,body);
	}/**

	 **
	 * Sets the content of media {@link #fileSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFileSecure(final com.exedio.cope.pattern.Media.Value fileSecure)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileSecure.set(this,fileSecure);
	}/**

	 **
	 * Sets the content of media {@link #fileSecure}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFileSecure(final byte[] body,final java.lang.String contentType)
	{
		MediaUrlItem.fileSecure.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fileSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFileSecure(final java.io.InputStream body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileSecure.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fileSecure}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFileSecure(final java.io.File body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileSecure.set(this,body,contentType);
	}/**

	 **
	 * Returns a Locator the content of {@link #fileFinger} is available under.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLocator public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final com.exedio.cope.pattern.MediaPath.Locator getFileFingerLocator()
	{
		return MediaUrlItem.fileFinger.getLocator(this);
	}/**

	 **
	 * Returns whether media {@link #fileFinger} is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isNull public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean isFileFingerNull()
	{
		return MediaUrlItem.fileFinger.isNull(this);
	}/**

	 **
	 * Returns the last modification date of media {@link #fileFinger}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLastModified public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final java.util.Date getFileFingerLastModified()
	{
		return MediaUrlItem.fileFinger.getLastModified(this);
	}/**

	 **
	 * Returns the body length of the media {@link #fileFinger}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getLength public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final long getFileFingerLength()
	{
		return MediaUrlItem.fileFinger.getLength(this);
	}/**

	 **
	 * Returns the body of the media {@link #fileFinger}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final byte[] getFileFingerBody()
	{
		return MediaUrlItem.fileFinger.getBody(this);
	}/**

	 **
	 * Writes the body of media {@link #fileFinger} into the given stream.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFileFingerBody(final java.io.OutputStream body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileFinger.getBody(this,body);
	}/**

	 **
	 * Writes the body of media {@link #fileFinger} into the given file.
	 * Does nothing, if the media is null.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getBody public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void getFileFingerBody(final java.io.File body)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileFinger.getBody(this,body);
	}/**

	 **
	 * Sets the content of media {@link #fileFinger}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFileFinger(final com.exedio.cope.pattern.Media.Value fileFinger)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileFinger.set(this,fileFinger);
	}/**

	 **
	 * Sets the content of media {@link #fileFinger}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFileFinger(final byte[] body,final java.lang.String contentType)
	{
		MediaUrlItem.fileFinger.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fileFinger}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFileFinger(final java.io.InputStream body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileFinger.set(this,body,contentType);
	}/**

	 **
	 * Sets the content of media {@link #fileFinger}.
	 * @throws java.io.IOException if accessing <tt>body</tt> throws an IOException.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setFileFinger(final java.io.File body,final java.lang.String contentType)
			throws
				java.io.IOException
	{
		MediaUrlItem.fileFinger.set(this,body,contentType);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for mediaUrlItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	public static final com.exedio.cope.Type<MediaUrlItem> TYPE = com.exedio.cope.TypesBound.newType(MediaUrlItem.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@SuppressWarnings("unused") private MediaUrlItem(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
