/*
 * Copyright (C) 2004-2015  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;

import com.exedio.cope.Item;
import com.exedio.cope.junit.AbsoluteMockClockStrategy;
import com.exedio.cope.pattern.PasswordLimiter.ExceededException;
import com.exedio.cope.tojunit.RelativeMockClockStrategy;

public final class PasswordLimiterItem extends Item
{
	static final Hash password = new Hash(MessageDigestHash.algorithm(8));
	static final PasswordLimiter passwordLimited = new PasswordLimiter(password, 1000, 2);

	final boolean checkPasswordLimited(
			final String password,
			final AbsoluteMockClockStrategy clock,
			final String date)
	{
		clock.add(date);
		final boolean result = checkPasswordLimited(password);
		clock.assertEmpty();
		return result;
	}

	final boolean checkPasswordLimitedVerbosely(final String password, final RelativeMockClockStrategy clock) throws ExceededException
	{
		clock.addNow();
		final boolean result = checkPasswordLimitedVerbosely(password);
		clock.assertEmpty();
		return result;
	}


	/**

	 **
	 * Creates a new PasswordLimiterItem with all the fields initially needed.
	 * @param password the initial value for field {@link #password}.
	 * @throws com.exedio.cope.MandatoryViolationException if password is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	PasswordLimiterItem(
				final java.lang.String password)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]{
			PasswordLimiterItem.password.map(password),
		});
	}/**

	 **
	 * Creates a new PasswordLimiterItem and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private PasswordLimiterItem(final com.exedio.cope.SetValue<?>... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Returns whether the given value corresponds to the hash in {@link #password}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.check public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean checkPassword(final java.lang.String password)
	{
		return PasswordLimiterItem.password.check(this,password);
	}/**

	 **
	 * Wastes (almost) as much cpu cycles, as a call to <tt>checkPassword</tt> would have needed.
	 * Needed to prevent Timing Attacks.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.blind public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final void blindPassword(final java.lang.String password)
	{
		PasswordLimiterItem.password.blind(password);
	}/**

	 **
	 * Sets a new value for {@link #password}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setPassword(final java.lang.String password)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		PasswordLimiterItem.password.set(this,password);
	}/**

	 **
	 * Returns the encoded hash value for hash {@link #password}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getSHA512s8i8 public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final java.lang.String getPasswordSHA512s8i8()
	{
		return PasswordLimiterItem.password.getHash(this);
	}/**

	 **
	 * Sets the encoded hash value for hash {@link #password}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setSHA512s8i8 public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setPasswordSHA512s8i8(final java.lang.String password)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		PasswordLimiterItem.password.setHash(this,password);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.check public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean checkPasswordLimited(final java.lang.String password)
	{
		return PasswordLimiterItem.passwordLimited.check(this,password);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.checkVerbosely public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean checkPasswordLimitedVerbosely(final java.lang.String password)
			throws
				com.exedio.cope.pattern.PasswordLimiter.ExceededException
	{
		return PasswordLimiterItem.passwordLimited.checkVerbosely(this,password);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.reset public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void resetPasswordLimited()
	{
		PasswordLimiterItem.passwordLimited.reset(this);
	}/**

	 **
	 * @return the number of refusals purged
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.purge public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@Deprecated
	static final int purgePasswordLimited(final com.exedio.cope.util.Interrupter interrupter)
	{
		return PasswordLimiterItem.passwordLimited.purge(interrupter);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.purge public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final void purgePasswordLimited(final com.exedio.cope.util.JobContext ctx)
	{
		PasswordLimiterItem.passwordLimited.purge(ctx);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for passwordLimiterItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	public static final com.exedio.cope.Type<PasswordLimiterItem> TYPE = com.exedio.cope.TypesBound.newType(PasswordLimiterItem.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@SuppressWarnings("unused") private PasswordLimiterItem(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
