/*
 * Copyright (C) 2004-2006  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.pattern;

import com.exedio.cope.Item;
import com.exedio.cope.StringField;

/**
 * @cope.generic.constructor package
 * @author Ralf Wiebicke
 */
public class RelationSourceItem extends Item
{
	public static final StringField code = new StringField(UNIQUE);
	
	/**

	 **
	 * Creates a new RelationSourceItem with all the fields initially needed.
	 * @param code the initial value for field {@link #code}.
	 * @throws com.exedio.cope.LengthViolationException if code violates its length constraint.
	 * @throws com.exedio.cope.MandatoryViolationException if code is null.
	 * @throws com.exedio.cope.UniqueViolationException if code is not unique.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	public RelationSourceItem(
				final java.lang.String code)
			throws
				com.exedio.cope.LengthViolationException,
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.UniqueViolationException
	{
		this(new com.exedio.cope.SetValue[]{
			RelationSourceItem.code.map(code),
		});
	}/**

	 **
	 * Creates a new RelationSourceItem and sets the given fields initially.
	 * This constructor is called by {@link com.exedio.cope.Type#newItem Type.newItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	RelationSourceItem(final com.exedio.cope.SetValue[] setValues)
	{
		super(setValues);
	}/**

	 **
	 * Reactivation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.util.ReactivationConstructorDummy,int)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private RelationSourceItem(com.exedio.cope.util.ReactivationConstructorDummy d,final int pk)
	{
		super(d,pk);
	}/**

	 **
	 * Returns the value of the persistent field {@link #code}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getter public|package|protected|private|none|non-final|boolean-as-is</tt> in the comment of the field.
	 */
	public final java.lang.String getCode()
	{
		return RelationSourceItem.code.get(this);
	}/**

	 **
	 * Sets a new value for the persistent field {@link #code}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setter public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final void setCode(final java.lang.String code)
			throws
				com.exedio.cope.LengthViolationException,
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.UniqueViolationException
	{
		RelationSourceItem.code.set(this,code);
	}/**

	 **
	 * Finds a relationSourceItem by it's unique fields.
	 * @param code shall be equal to field {@link #code}.
	 * @return null if there is no matching item.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public static final RelationSourceItem findByCode(final java.lang.String code)
	{
		return (RelationSourceItem)RelationSourceItem.code.searchUnique(code);
	}/**

	 **
	 * Returns the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final java.util.List<com.exedio.cope.pattern.RelationTargetItem> getTarget()
	{
		return com.exedio.cope.pattern.RelationItem.relation.getTargets(this);
	}/**

	 **
	 * Adds an item to the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final boolean addToTarget(final com.exedio.cope.pattern.RelationTargetItem target)
	{
		return com.exedio.cope.pattern.RelationItem.relation.addToTargets(this,target);
	}/**

	 **
	 * Removes an item from the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final boolean removeFromTarget(final com.exedio.cope.pattern.RelationTargetItem target)
	{
		return com.exedio.cope.pattern.RelationItem.relation.removeFromTargets(this,target);
	}/**

	 **
	 * Sets the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final void setTarget(final java.util.Collection<? extends com.exedio.cope.pattern.RelationTargetItem> target)
	{
		com.exedio.cope.pattern.RelationItem.relation.setTargets(this,target);
	}/**

	 **
	 * Returns the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final java.util.List<com.exedio.cope.pattern.RelationSourceItem> getSelfTarget()
	{
		return com.exedio.cope.pattern.RelationSelfItem.relation.getTargets(this);
	}/**

	 **
	 * Adds an item to the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final boolean addToSelfTarget(final com.exedio.cope.pattern.RelationSourceItem selfTarget)
	{
		return com.exedio.cope.pattern.RelationSelfItem.relation.addToTargets(this,selfTarget);
	}/**

	 **
	 * Removes an item from the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final boolean removeFromSelfTarget(final com.exedio.cope.pattern.RelationSourceItem selfTarget)
	{
		return com.exedio.cope.pattern.RelationSelfItem.relation.removeFromTargets(this,selfTarget);
	}/**

	 **
	 * Sets the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final void setSelfTarget(final java.util.Collection<? extends com.exedio.cope.pattern.RelationSourceItem> selfTarget)
	{
		com.exedio.cope.pattern.RelationSelfItem.relation.setTargets(this,selfTarget);
	}/**

	 **
	 * Returns the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final java.util.List<com.exedio.cope.pattern.RelationTargetItem> getVectorTarget()
	{
		return com.exedio.cope.pattern.VectorRelationItem.relation.getTargets(this);
	}/**

	 **
	 * Sets the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final void setVectorTarget(final java.util.Collection<? extends com.exedio.cope.pattern.RelationTargetItem> vectorTarget)
	{
		com.exedio.cope.pattern.VectorRelationItem.relation.setTargets(this,vectorTarget);
	}/**

	 **
	 * Returns the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final java.util.List<com.exedio.cope.pattern.RelationSourceItem> getSelfSource()
	{
		return com.exedio.cope.pattern.RelationSelfItem.relation.getSources(this);
	}/**

	 **
	 * Adds an item to the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final boolean addToSelfSource(final com.exedio.cope.pattern.RelationSourceItem selfSource)
	{
		return com.exedio.cope.pattern.RelationSelfItem.relation.addToSources(this,selfSource);
	}/**

	 **
	 * Removes an item from the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final boolean removeFromSelfSource(final com.exedio.cope.pattern.RelationSourceItem selfSource)
	{
		return com.exedio.cope.pattern.RelationSelfItem.relation.removeFromSources(this,selfSource);
	}/**

	 **
	 * Sets the items associated to this item by the relation.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	public final void setSelfSource(final java.util.Collection<? extends com.exedio.cope.pattern.RelationSourceItem> selfSource)
	{
		com.exedio.cope.pattern.RelationSelfItem.relation.setSources(this,selfSource);
	}/**

	 **
	 * The persistent type information for relationSourceItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	public static final com.exedio.cope.Type<RelationSourceItem> TYPE = newType(RelationSourceItem.class)
;}
