alter table "CollisionItem2" drop constraint "CollisItem2_colliAttri_Fk"
alter table "CollisionItem1" drop constraint "CollisItem1_colliAttri_Fk"
alter table "SecondSub" drop constraint "SecondSub_Sup"
alter table "FirstSub" drop constraint "FirstSub_Sup"
alter table "PointerItem" drop constraint "PointerItem_pointer_Fk"
alter table "PointerItem" drop constraint "PointerItem_pointer2_Fk"
alter table "PointerItem" drop constraint "PointerItem_self_Fk"
alter table "PointerItem" drop constraint "PointerItem_empty2_Fk"
alter table "QualifiIntegerEnumQualifi" drop constraint "QualiIntegEnumQuali_up_Fk"
alter table "QualifiedStringQualifier" drop constraint "QualifStringQuali_pare_Fk"
alter table "QualifiedEmptyQualifier" drop constraint "QualifEmptyQualif_pare_Fk"
alter table "QualifiedEmptyQualifier" drop constraint "QualifiEmptyQualif_key_Fk"
alter table "AttributeEmptyItem" drop constraint "AttribuEmptyItem_paren_Fk"
alter table "AttributeEmptyItem" drop constraint "AttributeEmptyItem_key_Fk"
alter table "AttributeItem" drop constraint "AttributeItem_someItem_Fk"
alter table "AttributeItem" drop constraint "AttrItem_somNotNullIte_Fk"
drop table "PLAN_TABLE"
drop table "CollisionItem2"
drop table "CollisionItem1"
drop table "SecondSub"
drop table "FirstSub"
drop table "Super"
drop table "PointerItem"
drop table "PointerTargetItem"
drop table "QualifiIntegerEnumQualifi"
drop table "QualifiedStringQualifier"
drop table "QualifiedEmptyQualifier"
drop table "QualifiedItem"
drop table "SumItem"
drop table "HttpEntityItem"
drop table "StringItem"
drop table "AttributeEmptyItem"
drop table "AttributeItem"
drop table "EmptyItem2"
drop table "EmptyItem"
drop table "ItemWithDoubleUnique"
drop table "ItemWithSinglUniquNotNull"
drop table "ItemWithSinglUniqReadOnly"
drop table "ItemWithSingleUnique"
