create table "ItemWithSingleUnique"("this" NUMBER(10),"uniqueString" VARCHAR2(2000),"otherString" VARCHAR2(2000),constraint "ItemWithSingleUnique_Pk" primary key("this"),constraint "ItemWithSingUni_unStr_Unq" unique("uniqueString"))
create table "ItemWithSinglUniqReadOnly"("this" NUMBER(10),"uniqueReadOnlyString" VARCHAR2(2000),constraint "ItemWithSingUniqReaOnl_Pk" primary key("this"),constraint "IteWitSiUnReOn_uReOnSt_Un" unique("uniqueReadOnlyString"))
create table "ItemWithSinglUniquNotNull"("this" NUMBER(10),"uniqueNotNullString" VARCHAR2(2000),constraint "ItemWithSingUniqNotNul_Pk" primary key("this"),constraint "IteWitSiUnNoNu_uNoNuSt_Ck" check("uniqueNotNullString" IS NOT NULL),constraint "IteWitSiUnNoNu_uNoNuSt_Un" unique("uniqueNotNullString"))
create table "ItemWithDoubleUnique"("this" NUMBER(10),"string" VARCHAR2(2000),"integer" NUMBER(10),constraint "ItemWithDoubleUnique_Pk" primary key("this"),constraint "ItemWithDoublUniqu_str_Ck" check("string" IS NOT NULL),constraint "ItemWithDoublUniqu_int_Ck" check("integer" IS NOT NULL),constraint "ItemWithDoubUni_doUni_Unq" unique("string","integer"))
create table "EmptyItem"("this" NUMBER(10),constraint "EmptyItem_Pk" primary key("this"))
create table "EmptyItem2"("this" NUMBER(10),constraint "EmptyItem2_Pk" primary key("this"))
create table "AttributeItem"("this" NUMBER(10),"someString" VARCHAR2(2000),"someNotNullString" VARCHAR2(2000),"someInteger" NUMBER(10),"someNotNullInteger" NUMBER(10),"someLong" NUMBER(20),"someNotNullLong" NUMBER(20),"someDouble" NUMBER(30,8),"someNotNullDouble" NUMBER(30,8),"someDate" TIMESTAMP(3),"someLongDate" NUMBER(20),"someBoolean" NUMBER(1),"someNotNullBoolean" NUMBER(1),"someItem" NUMBER(10),"someNotNullItem" NUMBER(10),"someEnum" NUMBER(10),"someNotNullEnum" NUMBER(10),"someDataMajor" VARCHAR2(30),"someDataMinor" VARCHAR2(30),constraint "AttributeItem_Pk" primary key("this"),constraint "AttrItem_somNotNullStr_Ck" check("someNotNullString" IS NOT NULL),constraint "AttrItem_somNotNullInt_Ck" check("someNotNullInteger" IS NOT NULL),constraint "AttrItem_somNotNullLon_Ck" check("someNotNullLong" IS NOT NULL),constraint "AttrItem_somNotNullDou_Ck" check("someNotNullDouble" IS NOT NULL),constraint "AttribuItem_someBoolea_Ck" check(("someBoolean" IN (0,1)) OR ("someBoolean" IS NULL)),constraint "AttrItem_somNotNullBoo_Ck" check(("someNotNullBoolean" IS NOT NULL) AND ("someNotNullBoolean" IN (0,1))),constraint "AttrItem_somNotNullIte_Ck" check("someNotNullItem" IS NOT NULL),constraint "AttributeItem_someEnum_Ck" check(("someEnum" IN (100,200,300)) OR ("someEnum" IS NULL)),constraint "AttrItem_somNotNullEnu_Ck" check(("someNotNullEnum" IS NOT NULL) AND ("someNotNullEnum" IN (100,200,300))),constraint "AttriItem_someDataMajo_Ck" check(((LENGTH("someDataMajor")>=1) AND (LENGTH("someDataMajor")<=30)) OR ("someDataMajor" IS NULL)),constraint "AttriItem_someDataMino_Ck" check(((LENGTH("someDataMinor")>=1) AND (LENGTH("someDataMinor")<=30)) OR ("someDataMinor" IS NULL)))
create table "AttributeEmptyItem"("this" NUMBER(10),"parent" NUMBER(10),"key" NUMBER(10),"someQualifiedString" VARCHAR2(2000),constraint "AttributeEmptyItem_Pk" primary key("this"),constraint "AttriEmptyItem_parKey_Unq" unique("parent","key"))
create table "StringItem"("this" NUMBER(10),"any" VARCHAR2(2000),"min4" VARCHAR2(2000),"max4" VARCHAR2(4),"min4Max8" VARCHAR2(8),"exact6" VARCHAR2(6),constraint "StringItem_Pk" primary key("this"),constraint "StringItem_min4_Ck" check((LENGTH("min4")>=4) OR ("min4" IS NULL)),constraint "StringItem_max4_Ck" check((LENGTH("max4")<=4) OR ("max4" IS NULL)),constraint "StringItem_min4Max8_Ck" check(((LENGTH("min4Max8")>=4) AND (LENGTH("min4Max8")<=8)) OR ("min4Max8" IS NULL)),constraint "StringItem_exact6_Ck" check((LENGTH("exact6")=6) OR ("exact6" IS NULL)))
create table "HttpEntityItem"("this" NUMBER(10),"fileMajor" VARCHAR2(30),"fileMinor" VARCHAR2(30),"imageMinor" VARCHAR2(30),"photoExists" NUMBER(1),constraint "HttpEntityItem_Pk" primary key("this"),constraint "HttpEntitItem_fileMajo_Ck" check(((LENGTH("fileMajor")>=1) AND (LENGTH("fileMajor")<=30)) OR ("fileMajor" IS NULL)),constraint "HttpEntitItem_fileMino_Ck" check(((LENGTH("fileMinor")>=1) AND (LENGTH("fileMinor")<=30)) OR ("fileMinor" IS NULL)),constraint "HttpEntitItem_imagMino_Ck" check(((LENGTH("imageMinor")>=1) AND (LENGTH("imageMinor")<=30)) OR ("imageMinor" IS NULL)),constraint "HttpEntitItem_photExis_Ck" check(("photoExists" IN (0,1)) OR ("photoExists" IS NULL)))
create table "SumItem"("this" NUMBER(10),"num1" NUMBER(10),"num2" NUMBER(10),"num3" NUMBER(10),constraint "SumItem_Pk" primary key("this"))
create table "QualifiedItem"("this" NUMBER(10),"number" NUMBER(10),constraint "QualifiedItem_Pk" primary key("this"))
create table "QualifiedEmptyQualifier"("this" NUMBER(10),"parent" NUMBER(10),"key" NUMBER(10),"qualifiedA" VARCHAR2(2000),"qualifiedB" VARCHAR2(2000),constraint "QualifiedEmptyQualifie_Pk" primary key("this"),constraint "QualifEmptyQualif_pare_Ck" check("parent" IS NOT NULL),constraint "QualifiEmptyQualif_key_Ck" check("key" IS NOT NULL),constraint "QualiEmptQual_quaUniq_Unq" unique("parent","key"))
create table "QualifiedStringQualifier"("this" NUMBER(10),"parent" NUMBER(10),"key" VARCHAR2(2000),"qualifiedA" NUMBER(10),"qualifiedB" NUMBER(10),constraint "QualifieStringQualifie_Pk" primary key("this"),constraint "QualifStringQuali_pare_Ck" check("parent" IS NOT NULL),constraint "QualifStringQualif_key_Ck" check("key" IS NOT NULL),constraint "QualiStriQual_quaUniq_Unq" unique("parent","key"))
create table "QualifiIntegerEnumQualifi"("this" NUMBER(10),"up" NUMBER(10),"keyX" NUMBER(10),"keyY" NUMBER(10),"qualifiedA" VARCHAR2(2000),"qualifiedB" VARCHAR2(2000),constraint "QualifIntegeEnumQualif_Pk" primary key("this"),constraint "QualiIntegEnumQuali_up_Ck" check("up" IS NOT NULL),constraint "QualiInteEnumQual_keyX_Ck" check("keyX" IS NOT NULL),constraint "QualiInteEnumQual_keyY_Ck" check(("keyY" IS NOT NULL) AND ("keyY" IN (100,200,300))),constraint "QualInteEnumQua_quUni_Unq" unique("up","keyX","keyY"))
create table "PointerTargetItem"("this" NUMBER(10),"code" VARCHAR2(2000),constraint "PointerTargetItem_Pk" primary key("this"),constraint "PointerTargetItem_code_Ck" check("code" IS NOT NULL))
create table "PointerItem"("this" NUMBER(10),"code" VARCHAR2(2000),"pointer" NUMBER(10),"pointer2" NUMBER(10),"self" NUMBER(10),"empty2" NUMBER(10),constraint "PointerItem_Pk" primary key("this"),constraint "PointerItem_code_Ck" check("code" IS NOT NULL),constraint "PointerItem_pointer_Ck" check("pointer" IS NOT NULL))
create table "Super"("this" NUMBER(10),"class" VARCHAR2(2000),"superInt" NUMBER(10),"superString" VARCHAR2(2000),constraint "Super_Pk" primary key("this"),constraint "Super_class_Ck" check(("class" IS NOT NULL) AND ("class" IN ('FirstSub','SecondSub'))),constraint "Super_superInt_Ck" check("superInt" IS NOT NULL))
create table "FirstSub"("this" NUMBER(10),"firstSubString" VARCHAR2(2000),constraint "FirstSub_Pk" primary key("this"))
create table "SecondSub"("this" NUMBER(10),"firstSubString" VARCHAR2(2000),constraint "SecondSub_Pk" primary key("this"))
create table "CollisionItem1"("this" NUMBER(10),"collisionAttribute" NUMBER(10),constraint "CollisionItem1_Pk" primary key("this"),constraint "CollisItem1_colliAttri_Ck" check("collisionAttribute" IS NOT NULL),constraint "CollisItem1_collAttri_Unq" unique("collisionAttribute"))
create table "CollisionItem2"("this" NUMBER(10),"collisionAttribute" NUMBER(10),constraint "CollisionItem2_Pk" primary key("this"),constraint "CollisItem2_colliAttri_Ck" check("collisionAttribute" IS NOT NULL),constraint "CollisItem2_collAttri_Unq" unique("collisionAttribute"))
create table "PLAN_TABLE"("STATEMENT_ID" VARCHAR2(30),"TIMESTAMP" DATE,"REMARKS" VARCHAR2(80),"OPERATION" VARCHAR2(30),"OPTIONS" VARCHAR2(30),"OBJECT_NODE" VARCHAR2(128),"OBJECT_OWNER" VARCHAR2(30),"OBJECT_NAME" VARCHAR2(30),"OBJECT_INSTANCE" NUMBER(22),"OBJECT_TYPE" VARCHAR2(30),"OPTIMIZER" VARCHAR2(255),"SEARCH_COLUMNS" NUMBER(22),"ID" NUMBER(22),"PARENT_ID" NUMBER(22),"POSITION" NUMBER(22),"COST" NUMBER(22),"CARDINALITY" NUMBER(22),"BYTES" NUMBER(22),"OTHER_TAG" VARCHAR2(255),"OTHER" LONG)
alter table "AttributeItem" add constraint "AttributeItem_someItem_Fk" foreign key ("someItem") references "EmptyItem"
alter table "AttributeItem" add constraint "AttrItem_somNotNullIte_Fk" foreign key ("someNotNullItem") references "EmptyItem"
alter table "AttributeEmptyItem" add constraint "AttribuEmptyItem_paren_Fk" foreign key ("parent") references "AttributeItem"
alter table "AttributeEmptyItem" add constraint "AttributeEmptyItem_key_Fk" foreign key ("key") references "EmptyItem"
alter table "QualifiedEmptyQualifier" add constraint "QualifEmptyQualif_pare_Fk" foreign key ("parent") references "QualifiedItem"
alter table "QualifiedEmptyQualifier" add constraint "QualifiEmptyQualif_key_Fk" foreign key ("key") references "EmptyItem"
alter table "QualifiedStringQualifier" add constraint "QualifStringQuali_pare_Fk" foreign key ("parent") references "QualifiedItem"
alter table "QualifiIntegerEnumQualifi" add constraint "QualiIntegEnumQuali_up_Fk" foreign key ("up") references "QualifiedItem"
alter table "PointerItem" add constraint "PointerItem_pointer_Fk" foreign key ("pointer") references "PointerTargetItem"
alter table "PointerItem" add constraint "PointerItem_pointer2_Fk" foreign key ("pointer2") references "PointerTargetItem"
alter table "PointerItem" add constraint "PointerItem_self_Fk" foreign key ("self") references "PointerItem"
alter table "PointerItem" add constraint "PointerItem_empty2_Fk" foreign key ("empty2") references "EmptyItem2"
alter table "FirstSub" add constraint "FirstSub_Sup" foreign key ("this") references "Super"
alter table "SecondSub" add constraint "SecondSub_Sup" foreign key ("this") references "Super"
alter table "CollisionItem1" add constraint "CollisItem1_colliAttri_Fk" foreign key ("collisionAttribute") references "EmptyItem"
alter table "CollisionItem2" add constraint "CollisItem2_colliAttri_Fk" foreign key ("collisionAttribute") references "EmptyItem"
