/*
 * Copyright (C) 2004-2015  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.instrument.testmodel;


class SubOfInnerSub extends InnerContainer.Sub
{


/**

	 **
	 * Creates a new SubOfInnerSub with all the fields initially needed.
	 * @param superMandatory the initial value for field {@link #superMandatory}.
	 * @param superInitial the initial value for field {@link #superInitial}.
	 * @param subField the initial value for field {@link #subField}.
	 * @param subReference the initial value for field {@link #subReference}.
	 * @throws com.exedio.cope.MandatoryViolationException if superMandatory, subField, subReference is null.
	 * @throws com.exedio.cope.StringLengthViolationException if superMandatory, subField violates its length constraint.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	SubOfInnerSub(
				@javax.annotation.Nonnull final java.lang.String superMandatory,
				@javax.annotation.Nullable final java.lang.Integer superInitial,
				@javax.annotation.Nonnull final java.lang.String subField,
				@javax.annotation.Nonnull final com.exedio.cope.instrument.testmodel.InnerContainer.Sub subReference)
			throws
				com.exedio.cope.MandatoryViolationException,
				com.exedio.cope.StringLengthViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]{
			com.exedio.cope.instrument.testmodel.Super.superMandatory.map(superMandatory),
			com.exedio.cope.instrument.testmodel.Super.superInitial.map(superInitial),
			com.exedio.cope.instrument.testmodel.InnerContainer.Sub.subField.map(subField),
			com.exedio.cope.instrument.testmodel.InnerContainer.Sub.subReference.map(subReference),
		});
	}/**

	 **
	 * Creates a new SubOfInnerSub and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	protected SubOfInnerSub(final com.exedio.cope.SetValue<?>... setValues)
	{
		super(setValues);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for subOfInnerSub.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@SuppressWarnings("hiding")
	static final com.exedio.cope.Type<SubOfInnerSub> TYPE = com.exedio.cope.TypesBound.newType(SubOfInnerSub.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	protected SubOfInnerSub(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
